import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { Course, CourseCategory, CourseLevel } from '../src/database/models/Course.model';
import { CourseConfig } from '../src/database/models/CourseConfig.model';

dotenv.config({ path: path.join(__dirname, '../.env') });

const logger = {
  info: (msg: string) => console.log(`[INFO] ${msg}`),
  warn: (msg: string) => console.warn(`[WARN] ${msg}`),
  error: (msg: string, error?: any) => console.error(`[ERROR] ${msg}`, error || ''),
};

export interface CourseSet2Item {
  sNo: number;
  title: string;
  slug: string;
  category: CourseCategory;
  subcategory: string;
  level: CourseLevel;
  difficultyLevel: string;
  duration: number;
  lessonsCount: number;
  keyTopics: string[];
  targetAudience: string;
  prerequisites: string;
  deliveryMode: string;
  certificate: string;
  funnelTier: string;
  marketingAngle: string;
  suggestedKeyword: string;
  price: number;
  originalPrice: number;
  rating: number;
  shortDescription: string;
  description: string;
  tags: string[];
  instructor: {
    name: string;
    avatar?: string;
  };
}

export const coursesSet2Data: CourseSet2Item[] = [
  {
    sNo: 1,
    title: 'CodeCraft: Python 101',
    slug: 'codecraft-python-101-v2',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Core Programming',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['Python Basics', 'Data Types', 'Loops', 'Functions'],
    targetAudience: 'First-year students, complete beginners',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Entry-level programming gateway',
    suggestedKeyword: 'Learn Python coding',
    price: 2499,
    originalPrice: 4999,
    rating: 4.9,
    shortDescription: 'Entry-level programming gateway. Master Python syntax, data types, loops, and functions.',
    description: 'Learn Python from first principles. Master variables, standard data structures, flow control, reusable functions, and hands-on coding exercises built for first-year and beginner students.',
    tags: ['Python Basics', 'Data Types', 'Loops', 'Functions', 'Core Programming', 'Learn Python coding'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 2,
    title: 'Java, C++, C# Quad Core: Multi Language',
    slug: 'java-cpp-csharp-quad-core-multi-language',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Core Programming',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 35,
    lessonsCount: 28,
    keyTopics: ['Java', 'C++', 'C#', 'OOP', 'Error Handling'],
    targetAudience: 'Multi-language exposure seekers',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Multi-language versatility',
    suggestedKeyword: 'Java C++ C# course',
    price: 3999,
    originalPrice: 7999,
    rating: 4.8,
    shortDescription: 'Multi-language versatility. Compare and master Java, C++, and C# with OOP principles.',
    description: 'Master multi-language software development. Learn object-oriented paradigms across Java, C++, and C#, comparing memory models, error handling strategies, and language features.',
    tags: ['Java', 'C++', 'C#', 'OOP', 'Error Handling', 'Multi Language', 'Java C++ C# course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 3,
    title: 'AlgoCore: Mastering DSA (Set 2)',
    slug: 'algocore-mastering-dsa-concepts',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'DS Concepts',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 45,
    lessonsCount: 35,
    keyTopics: ['Arrays', 'Linked Lists', 'Trees', 'Graphs'],
    targetAudience: 'Placement preparing students',
    prerequisites: 'Basic programming',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Interview readiness essential',
    suggestedKeyword: 'DSA mastery course',
    price: 4499,
    originalPrice: 8999,
    rating: 4.9,
    shortDescription: 'Interview readiness essential. Master core arrays, linked lists, trees, and graphs.',
    description: 'Essential data structures and algorithms mastery for campus interview readiness. In-depth coverage of arrays, singly/doubly linked lists, binary trees, BSTs, traversal, and graph algorithms.',
    tags: ['Arrays', 'Linked Lists', 'Trees', 'Graphs', 'DSA Concepts', 'DSA mastery course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 4,
    title: 'CP Sprint: Competitive Coding Bootcamp (Set 2)',
    slug: 'cp-sprint-competitive-coding-contest',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Competitive',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 40,
    lessonsCount: 30,
    keyTopics: ['Codeforces', 'AtCoder', 'LeetCode'],
    targetAudience: 'Advanced competitive coders',
    prerequisites: 'Strong DSA',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Elite competitive coding',
    suggestedKeyword: 'Competitive programming training',
    price: 5499,
    originalPrice: 10999,
    rating: 4.9,
    shortDescription: 'Elite competitive coding. Master contest problem solving on Codeforces, AtCoder, and LeetCode.',
    description: 'Intensive competitive programming bootcamp designed for online contest leaderboards and high-frequency technical screens on Codeforces, AtCoder, and LeetCode Hard problems.',
    tags: ['Codeforces', 'AtCoder', 'LeetCode', 'Competitive Programming', 'Algorithms', 'Competitive programming training'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 5,
    title: 'HTML5 Essentials: Web Basics',
    slug: 'html5-essentials-web-basics',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Frontend Development',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 14,
    lessonsCount: 12,
    keyTopics: ['HTML5 Tags', 'Forms', 'SEO Tags', 'Semantic HTML'],
    targetAudience: 'Complete web beginners',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Quick web start — learn HTML',
    suggestedKeyword: 'Learn HTML basics',
    price: 1499,
    originalPrice: 2999,
    rating: 4.8,
    shortDescription: 'Quick web start — learn HTML. Semantic markup, accessible forms, and on-page SEO tags.',
    description: 'Learn modern semantic HTML5 from the ground up. Covers page structure, headings, semantic tags, interactive form validation, accessibility attributes, and SEO metadata.',
    tags: ['HTML5 Tags', 'Forms', 'SEO Tags', 'Semantic HTML', 'Frontend', 'Learn HTML basics'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 6,
    title: 'CSS3 for Creators: Modern Styling',
    slug: 'css3-for-creators-modern-styling',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Frontend Development',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['CSS3', 'Flexbox', 'Grid', 'Animations', 'Responsive Layouts'],
    targetAudience: 'Students with HTML knowledge',
    prerequisites: 'HTML',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Visual result design-heavy layout design',
    suggestedKeyword: 'CSS styling masterclass',
    price: 2499,
    originalPrice: 4999,
    rating: 4.9,
    shortDescription: 'Visual result design-heavy layout design. Master Flexbox, CSS Grid, animations, and responsive UI.',
    description: 'Build visually stunning web layouts with CSS3. Master modern Flexbox alignments, complex CSS Grid systems, keyframe animations, smooth transitions, and responsive mobile-first design.',
    tags: ['CSS3', 'Flexbox', 'Grid', 'Animations', 'Responsive Layouts', 'CSS styling masterclass'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 7,
    title: 'JavaScript Launchpad',
    slug: 'javascript-launchpad',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Frontend Development',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['DOM', 'Events', 'Async Fetch API', 'ES6+', 'Arrays/Dicts'],
    targetAudience: 'Frontend students ready for interactivity',
    prerequisites: 'HTML + CSS basics',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: '"Just JavaScript" — highest SEO keyword',
    suggestedKeyword: 'JavaScript course India',
    price: 2999,
    originalPrice: 5999,
    rating: 4.9,
    shortDescription: '"Just JavaScript" — highest SEO keyword. Master modern ES6+, DOM events, and Async Fetch API.',
    description: 'Unlock modern browser JavaScript. Learn ES6+ arrow functions, destructuring, modules, DOM tree manipulation, event listeners, Promises, and asynchronous data fetching with Fetch API.',
    tags: ['DOM', 'Events', 'Async Fetch API', 'ES6+', 'Arrays/Dicts', 'JavaScript', 'JavaScript course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 8,
    title: 'React Sprint: Modern UI Dev',
    slug: 'react-sprint-modern-ui-dev',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Frontend Development',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['React Hooks', 'Context API', 'Next Router', 'State Management'],
    targetAudience: 'JS proficient developers moving to React',
    prerequisites: 'JavaScript Launchpad',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Most in-demand framework',
    suggestedKeyword: 'React js course training',
    price: 3999,
    originalPrice: 7999,
    rating: 4.9,
    shortDescription: 'Most in-demand framework. Master React Hooks, Context API state management, and Next Router.',
    description: 'Fast-track your React development skills. Build component-driven web apps with custom hooks, Context API global state, efficient rerender optimization, and Next.js page routing.',
    tags: ['React Hooks', 'Context API', 'Next Router', 'State Management', 'React', 'React js course training'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 9,
    title: 'Vue Vibes: Vue.js 3',
    slug: 'vue-vibes-vuejs-3',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Frontend Development',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Vue Directives', 'State Management', 'Vue Router', 'Composition API'],
    targetAudience: 'Developers wanting Vue.js skills',
    prerequisites: 'JavaScript proficiency',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Enterprise framework alternative',
    suggestedKeyword: 'Vue js course India',
    price: 2999,
    originalPrice: 5999,
    rating: 4.7,
    shortDescription: 'Enterprise framework alternative. Master Vue 3 directives, Composition API, and Vue Router.',
    description: 'Learn modern Vue.js 3 development. Covers template directives (v-if, v-for, v-model), Composition API setup scripts, reactive state, computed properties, and Vue Router navigation.',
    tags: ['Vue Directives', 'State Management', 'Vue Router', 'Composition API', 'Vue.js', 'Vue js course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 10,
    title: 'Backend Basics: Node.js & Express',
    slug: 'backend-basics-nodejs-express',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Backend Development',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Express Setup', 'Routing', 'Middleware', 'Error Handling'],
    targetAudience: 'Frontend devs looking to learn backend',
    prerequisites: 'JavaScript Launchpad',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Server-side entry point',
    suggestedKeyword: 'Node.js Express course',
    price: 2999,
    originalPrice: 5999,
    rating: 4.8,
    shortDescription: 'Server-side entry point. Master Express server setup, REST routing, middleware, and errors.',
    description: 'The fastest path to backend development for JavaScript programmers. Learn Node.js HTTP servers, Express routing, custom middleware pipelines, request parsing, and centralized error handling.',
    tags: ['Express Setup', 'Routing', 'Middleware', 'Error Handling', 'Node.js', 'Node.js Express course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 11,
    title: 'Django Drive: Python Backend',
    slug: 'django-drive-python-backend',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Backend Development',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['ORM', 'Django Admin', 'API', 'MVT', 'Serializers'],
    targetAudience: 'Python developers wanting web backend',
    prerequisites: 'Python proficiency',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Python backend alternative',
    suggestedKeyword: 'Django backend training',
    price: 3499,
    originalPrice: 6999,
    rating: 4.8,
    shortDescription: 'Python backend alternative. Build robust web backends with Django ORM, Admin, and REST APIs.',
    description: 'Develop enterprise-grade Python backends with Django. Master Model-View-Template architecture, database models, Django ORM querying, admin site configuration, and Django REST Framework serializers.',
    tags: ['ORM', 'Django Admin', 'API', 'MVT', 'Serializers', 'Django', 'Django backend training'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 12,
    title: 'Full Stack Forge: MERN Bootcamp',
    slug: 'full-stack-forge-mern-bootcamp',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Fullstack',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 45,
    lessonsCount: 36,
    keyTopics: ['MongoDB', 'Express', 'React', 'Node', 'Auth', 'Deploy'],
    targetAudience: 'Students targeting full-stack roles',
    prerequisites: 'React + Node proficiency',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'MERN Mastery feeder course',
    suggestedKeyword: 'MERN Bootcamp India',
    price: 5999,
    originalPrice: 11999,
    rating: 4.9,
    shortDescription: 'MERN Mastery feeder course. Build end-to-end applications with MongoDB, Express, React, and Node.',
    description: 'Hands-on full-stack engineering boot camp. Integrate MongoDB Mongoose schemas, Express REST controllers, React single-page UI, JWT authentication, and production cloud deployment.',
    tags: ['MongoDB', 'Express', 'React', 'Node', 'Auth', 'Deploy', 'MERN', 'MERN Bootcamp India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 13,
    title: 'Next.js Ninja: Fullstack React',
    slug: 'nextjs-ninja-fullstack-react',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Fullstack',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['SSR', 'SSG', 'App Routing', 'API Routes', 'Middleware'],
    targetAudience: 'React developers wanting Next.js',
    prerequisites: 'React + JavaScript or React basics',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Modern framework, production-grade',
    suggestedKeyword: 'Next.js fullstack training',
    price: 4499,
    originalPrice: 8999,
    rating: 4.9,
    shortDescription: 'Modern framework, production-grade. Master Next.js App Router, SSR, SSG, and API routes.',
    description: 'Next-generation full-stack React with Next.js. Master Server-Side Rendering (SSR), Static Site Generation (SSG), App Router directory structure, Server Components, API routes, and edge middleware.',
    tags: ['SSR', 'SSG', 'App Routing', 'API Routes', 'Middleware', 'Next.js', 'Next.js fullstack training'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 14,
    title: 'Py for Data: Python for Data Science',
    slug: 'py-for-data-python-for-data-science',
    category: CourseCategory.DATA_SCIENCE,
    subcategory: 'Data Science',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['NumPy', 'Pandas', 'Matplotlib', 'Data Cleaning', 'Visualization'],
    targetAudience: 'Students starting data pathway',
    prerequisites: 'Basic computer literacy',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Data science gateway course',
    suggestedKeyword: 'Python data science course',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'Data science gateway course. Master NumPy, Pandas, Matplotlib data cleaning, and charts.',
    description: 'The foundation for data science in Python. Learn vectorized computations with NumPy, table manipulation with Pandas, data sanitization techniques, and plotting charts with Matplotlib & Seaborn.',
    tags: ['NumPy', 'Pandas', 'Matplotlib', 'Data Cleaning', 'Visualization', 'Python data science course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 15,
    title: 'SQL Skills Builder',
    slug: 'sql-skills-builder',
    category: CourseCategory.DATA_SCIENCE,
    subcategory: 'Databases & SQL',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Joins', 'Aggregates', 'Subqueries', 'Window Functions', 'Indexing'],
    targetAudience: 'Anyone needing database query skills',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Universal database skill',
    suggestedKeyword: 'SQL course beginners',
    price: 2499,
    originalPrice: 4999,
    rating: 4.9,
    shortDescription: 'Universal database skill. Master SQL Joins, Aggregates, Subqueries, and Window Functions.',
    description: 'Essential relational SQL querying for developers and analysts. Learn complex multi-table JOINs, GROUP BY aggregations, nested subqueries, CTEs, window functions (ROW_NUMBER, RANK), and query indexing.',
    tags: ['Joins', 'Aggregates', 'Subqueries', 'Window Functions', 'Indexing', 'SQL', 'SQL course beginners'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 16,
    title: 'DataShift: Excel & Google Sheets',
    slug: 'datashift-excel-google-sheets',
    category: CourseCategory.DATA_SCIENCE,
    subcategory: 'Analytics Tools',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 16,
    lessonsCount: 12,
    keyTopics: ['Functions', 'Pivot Tables', 'Visualization', 'VLOOKUP', 'Dashboard Formatting'],
    targetAudience: 'Non-technical students, business track',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Lowest-barrier analytical course',
    suggestedKeyword: 'Excel Google Sheets training',
    price: 1999,
    originalPrice: 3999,
    rating: 4.8,
    shortDescription: 'Lowest-barrier analytical course. Master Pivot Tables, VLOOKUP/XLOOKUP, and dashboards.',
    description: 'Spreadsheet analytics for high productivity. Learn essential formulas (VLOOKUP, XLOOKUP, INDEX/MATCH), Pivot Tables, conditional formatting, dynamic charts, and executive dashboard layout in Excel & Google Sheets.',
    tags: ['Functions', 'Pivot Tables', 'Visualization', 'VLOOKUP', 'Dashboard Formatting', 'Excel Google Sheets training'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 17,
    title: 'Power Up & BI: Power BI for Beginners',
    slug: 'power-up-and-bi-power-bi-beginners',
    category: CourseCategory.DATA_SCIENCE,
    subcategory: 'Analytics Tools',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['DAX', 'Power Query', 'Dashboards', 'Data Modeling', 'Report Publishing'],
    targetAudience: 'Business/analytics students',
    prerequisites: 'DataShift or spreadsheet comfort',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Recruiter-visible BI skill',
    suggestedKeyword: 'Power BI course India',
    price: 3499,
    originalPrice: 6999,
    rating: 4.8,
    shortDescription: 'Recruiter-visible BI skill. Master DAX expressions, Power Query transformations, and reports.',
    description: 'Transform raw data tables into interactive Power BI reports. Learn ETL in Power Query, star schema data modeling, essential DAX calculations (CALCULATE, RELATED), and publishing interactive executive dashboards.',
    tags: ['DAX', 'Power Query', 'Dashboards', 'Data Modeling', 'Report Publishing', 'Power BI', 'Power BI course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 18,
    title: 'Tableau Visuals: BI for Data',
    slug: 'tableau-visuals-bi-for-data',
    category: CourseCategory.DATA_SCIENCE,
    subcategory: 'Analytics Tools',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Calculated Fields', 'Stories', 'Dashboard Actions', 'Published Dashboards'],
    targetAudience: 'Visual-leaning analytics students',
    prerequisites: 'Basic data familiarity',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Alternative BI platform skill',
    suggestedKeyword: 'Tableau visualization course',
    price: 2999,
    originalPrice: 5999,
    rating: 4.8,
    shortDescription: 'Alternative BI platform skill. Build interactive Tableau charts, storyboards, and dashboards.',
    description: 'Master visual data storytelling with Tableau Desktop. Learn calculated fields, Level of Detail (LOD) expressions, interactive dashboard actions, storyboards, and publishing to Tableau Public/Server.',
    tags: ['Calculated Fields', 'Stories', 'Dashboard Actions', 'Published Dashboards', 'Tableau', 'Tableau visualization course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 19,
    title: 'ML Quick Intro: Intro to Machine Learning',
    slug: 'ml-quick-intro-machine-learning',
    category: CourseCategory.DATA_SCIENCE,
    subcategory: 'Machine Learning',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Linear Regression', 'Classification', 'Feature Engineering', 'Train-Test Split', 'Scikit-learn'],
    targetAudience: 'Students with Python and stats basics',
    prerequisites: 'PyData or Python + basic stats',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'ML foundation course',
    suggestedKeyword: 'Machine learning beginner course',
    price: 3999,
    originalPrice: 7999,
    rating: 4.9,
    shortDescription: 'ML foundation course. Master regression, classification, train-test splits, and Scikit-learn.',
    description: 'Applied machine learning fundamentals with Python. Learn feature scaling, one-hot encoding, train-test splitting, linear/logistic regression, decision trees, cross-validation, and Scikit-learn pipelines.',
    tags: ['Linear Regression', 'Classification', 'Feature Engineering', 'Train-Test Split', 'Scikit-learn', 'Machine learning beginner course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 20,
    title: 'DeepDive AI: Neural Networks & Deep Learning',
    slug: 'deepdive-ai-neural-networks-deep-learning',
    category: CourseCategory.AI_ML,
    subcategory: 'Deep Learning',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 40,
    lessonsCount: 30,
    keyTopics: ['CNNs', 'RNNs', 'PyTorch', 'Transfer Learning', 'Model Optimization'],
    targetAudience: 'Advanced ML students, research-focused',
    prerequisites: 'ML QuickIntro or equivalent',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Deep learning specialization',
    suggestedKeyword: 'Neural networks deep learning',
    price: 5499,
    originalPrice: 10999,
    rating: 4.9,
    shortDescription: 'Deep learning specialization. Master PyTorch, CNNs, RNNs, and transfer learning models.',
    description: 'Deep dive into modern neural architectures using PyTorch. Covers multi-layer perceptrons, backpropagation, Convolutional Neural Networks (CNNs) for vision, Recurrent networks for sequences, and transfer learning.',
    tags: ['CNNs', 'RNNs', 'PyTorch', 'Transfer Learning', 'Model Optimization', 'Deep Learning', 'Neural networks deep learning'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 21,
    title: 'NLP Navigator: Text & GenAI',
    slug: 'nlp-navigator-text-genai',
    category: CourseCategory.AI_ML,
    subcategory: 'Machine Learning',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Tokenization', 'Transformers', 'HuggingFace', 'NLTK', 'Sentiment Analysis', 'Text Generation'],
    targetAudience: 'AI/ML students specializing in language',
    prerequisites: 'ML QuickIntro or strong ML foundation',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'NLP specialization; GenAI adjacent',
    suggestedKeyword: 'NLP transformers course India',
    price: 4999,
    originalPrice: 9999,
    rating: 4.9,
    shortDescription: 'NLP specialization; GenAI adjacent. Master HuggingFace Transformers, tokenization, and text generation.',
    description: 'Natural Language Processing and Transformer models. Learn tokenization pipelines, NLTK/SpaCy processing, Hugging Face pretrained models (BERT, GPT), sentiment classifiers, and generative text workflows.',
    tags: ['Tokenization', 'Transformers', 'HuggingFace', 'NLTK', 'Sentiment Analysis', 'Text Generation', 'NLP transformers course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 22,
    title: 'DevOps Drive: Foundations',
    slug: 'devops-drive-foundations',
    category: CourseCategory.DEVOPS,
    subcategory: 'DevOps',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['DevOps Lifecycle', 'CI/CD Concepts', 'Agile + DevOps Integration'],
    targetAudience: 'Students wanting DevOps operation skills',
    prerequisites: 'Basic computer literacy/Git familiarity',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'DevOps fundamentals',
    suggestedKeyword: 'DevOps foundations course',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'DevOps fundamentals. Learn DevOps lifecycle, continuous integration, and team delivery culture.',
    description: 'Core concepts of modern DevOps engineering. Understand continuous integration and deployment loops, infrastructure as code concepts, monitoring feedback loops, and agile operations collaboration.',
    tags: ['DevOps Lifecycle', 'CI/CD Concepts', 'Agile + DevOps Integration', 'DevOps', 'DevOps foundations course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 23,
    title: 'CI/CD Crash Course',
    slug: 'cicd-crash-course-jenkins-actions',
    category: CourseCategory.DEVOPS,
    subcategory: 'DevOps',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 22,
    lessonsCount: 18,
    keyTopics: ['Jenkins', 'GitHub Actions', 'Pipelines', 'Automated Testing', 'Deployment Strategies'],
    targetAudience: 'DevOps-track students',
    prerequisites: 'DevOps Drive or Git proficiency',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Automation-focused; pipeline skills',
    suggestedKeyword: 'CI CD Jenkins GitHub Actions',
    price: 3499,
    originalPrice: 6999,
    rating: 4.9,
    shortDescription: 'Automation-focused; pipeline skills. Build automated pipelines with GitHub Actions & Jenkins.',
    description: 'Automate build, test, and release workflows. Master YAML pipeline configuration in GitHub Actions, Jenkins multi-branch pipelines, runner setup, automated lint/test execution, and blue-green deployment triggers.',
    tags: ['Jenkins', 'GitHub Actions', 'Pipelines', 'Automated Testing', 'Deployment Strategies', 'CI CD Jenkins GitHub Actions'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 24,
    title: 'CloudBase: AWS, Azure, GCP',
    slug: 'cloudbase-aws-azure-gcp-starter',
    category: CourseCategory.CLOUD_COMPUTING,
    subcategory: 'Cloud Providers',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['Cloud Models', 'Compute', 'Storage', 'IAM', 'Costing'],
    targetAudience: 'Students entering cloud computing',
    prerequisites: 'Basic networking and Linux',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Multi-cloud awareness; cert prep starter',
    suggestedKeyword: 'AWS Azure GCP beginner course',
    price: 2999,
    originalPrice: 5999,
    rating: 4.8,
    shortDescription: 'Multi-cloud awareness; cert prep starter. Understand compute, storage, and IAM across AWS, Azure, GCP.',
    description: 'Foundational multi-cloud overview across AWS, Azure, and Google Cloud Platform. Learn cloud delivery models (IaaS/PaaS/SaaS), virtual compute instances, object storage buckets, IAM permissions, and billing optimization.',
    tags: ['Cloud Models', 'Compute', 'Storage', 'IAM', 'Costing', 'Cloud Computing', 'AWS Azure GCP beginner course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 25,
    title: 'CloudBuilder: AWS Projects',
    slug: 'cloudbuilder-aws-projects',
    category: CourseCategory.CLOUD_COMPUTING,
    subcategory: 'Cloud Providers',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 35,
    lessonsCount: 28,
    keyTopics: ['Lambda', 'S3', 'DynamoDB', 'API Gateway', 'Serverless Patterns'],
    targetAudience: 'AWS-focused students; project builders',
    prerequisites: 'CloudBase or AWS fundamentals',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Hands-on AWS projects; portfolio builder',
    suggestedKeyword: 'AWS projects course India',
    price: 4499,
    originalPrice: 8999,
    rating: 4.9,
    shortDescription: 'Hands-on AWS projects; portfolio builder. Build serverless architectures on Lambda, S3, and DynamoDB.',
    description: 'Deploy real serverless cloud applications on AWS. Master AWS Lambda function triggers, API Gateway endpoints, Amazon S3 static website hosting, DynamoDB NoSQL querying, and CloudWatch metrics.',
    tags: ['Lambda', 'S3', 'DynamoDB', 'API Gateway', 'Serverless Patterns', 'AWS', 'AWS projects course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 26,
    title: 'Docker Domination',
    slug: 'docker-domination-course',
    category: CourseCategory.DEVOPS,
    subcategory: 'Containers',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Dockerfile', 'Compose', 'Volumes', 'Networking', 'Multi-stage Builds'],
    targetAudience: 'Developers wanting containerization skills',
    prerequisites: 'Basic Linux/command-line CLI',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Container-specific depth',
    suggestedKeyword: 'Docker course India',
    price: 2999,
    originalPrice: 5999,
    rating: 4.9,
    shortDescription: 'Container-specific depth. Master Dockerfile optimization, Compose, volumes, and multi-stage builds.',
    description: 'Complete hands-on container engineering with Docker. Learn image layers, writing lean multi-stage Dockerfiles, persistent data volumes, custom bridge networking, and multi-service orchestration with Docker Compose.',
    tags: ['Dockerfile', 'Compose', 'Volumes', 'Networking', 'Multi-stage Builds', 'Docker', 'Docker course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 27,
    title: 'Kubernetes Kraft',
    slug: 'kubernetes-kraft-course',
    category: CourseCategory.DEVOPS,
    subcategory: 'Containers',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Pods', 'Services', 'Deployments', 'ConfigMaps', 'Ingress', 'Helm'],
    targetAudience: 'Container-proficient developers',
    prerequisites: 'Docker Domination',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Orchestration mastery; DevOps cornerstone',
    suggestedKeyword: 'Kubernetes course training',
    price: 4999,
    originalPrice: 9999,
    rating: 4.9,
    shortDescription: 'Orchestration mastery; DevOps cornerstone. Master Pods, Deployments, Services, and Helm charts.',
    description: 'Enterprise Kubernetes cluster administration and deployment. Master Pod resource limits, ReplicaSets, RollingUpdate Deployments, ClusterIP/NodePort Services, Ingress controllers, ConfigMaps, Secrets, and Helm packaging.',
    tags: ['Pods', 'Services', 'Deployments', 'ConfigMaps', 'Ingress', 'Helm', 'Kubernetes', 'Kubernetes course training'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 28,
    title: 'CyberStart: Intro to Cybersecurity',
    slug: 'cyberstart-intro-to-cybersecurity',
    category: CourseCategory.CYBERSECURITY,
    subcategory: 'Fundamentals',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 18,
    lessonsCount: 14,
    keyTopics: ['Threat Landscape', 'Passwords', 'Security Hygiene', 'Common Attacks'],
    targetAudience: 'Students curious about information security',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Cybersecurity awareness for all',
    suggestedKeyword: 'Cybersecurity beginner course',
    price: 1999,
    originalPrice: 3999,
    rating: 4.8,
    shortDescription: 'Cybersecurity awareness for all. Understand cyber threat landscape, attack vectors, and hygiene.',
    description: 'Foundational information security principles. Explore common threat vectors (phishing, malware, social engineering), credential security, multi-factor authentication, safe browsing, and essential data encryption.',
    tags: ['Threat Landscape', 'Passwords', 'Security Hygiene', 'Common Attacks', 'Cybersecurity', 'Cybersecurity beginner course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 29,
    title: 'Ethical Hacker Express',
    slug: 'ethical-hacker-express',
    category: CourseCategory.CYBERSECURITY,
    subcategory: 'Advanced Security',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['Kali Linux', 'Scanning', 'Metasploit', 'Reconnaissance', 'Vulnerability Assessment'],
    targetAudience: 'Security-interested students with Linux skills',
    prerequisites: 'CyberStart + basic Linux',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Hands-on hacking skills',
    suggestedKeyword: 'Ethical hacking course India',
    price: 3999,
    originalPrice: 7999,
    rating: 4.9,
    shortDescription: 'Hands-on hacking skills. Master Kali Linux, Nmap network scanning, Metasploit, and assessment.',
    description: 'Practical offensive security methodology. Master Kali Linux toolsets, passive and active network reconnaissance using Nmap, vulnerability scanning with OpenVAS, exploit staging in Metasploit, and reporting.',
    tags: ['Kali Linux', 'Scanning', 'Metasploit', 'Reconnaissance', 'Vulnerability Assessment', 'Ethical hacking course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 30,
    title: 'Bug Bounty Basics',
    slug: 'bug-bounty-basics-guide',
    category: CourseCategory.CYBERSECURITY,
    subcategory: 'Advanced Security',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['XSS', 'SQLi', 'IDOR', 'Bug Bounty Platforms', 'Report Writing'],
    targetAudience: 'Aspiring bug bounty hunters',
    prerequisites: 'Ethical Hacker Express',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Earn while you learn angle',
    suggestedKeyword: 'Bug bounty training course',
    price: 3499,
    originalPrice: 6999,
    rating: 4.9,
    shortDescription: 'Earn while you learn angle. Find web vulnerabilities (XSS, SQLi, IDOR) on bug bounty platforms.',
    description: 'Find security vulnerabilities and earn bug bounties. Learn to spot Insecure Direct Object References (IDOR), Cross-Site Scripting (XSS), SQL injections, navigation of HackerOne/Bugcrowd, and writing professional disclosure reports.',
    tags: ['XSS', 'SQLi', 'IDOR', 'Bug Bounty Platforms', 'Report Writing', 'Cybersecurity', 'Bug bounty training course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 31,
    title: 'NetDefend: Network Security',
    slug: 'netdefend-network-security',
    category: CourseCategory.CYBERSECURITY,
    subcategory: 'Advanced Security',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['OSI Model', 'Firewalls', 'IDS/IPS', 'VPN', 'Network Monitoring'],
    targetAudience: 'Networking curious students',
    prerequisites: 'Basic networking concepts',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Network defense & infrastructure security',
    suggestedKeyword: 'Network security course',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'Network defense & infrastructure security. Learn OSI layers, firewalls, IDS/IPS, and VPNs.',
    description: 'Defensive network engineering. Understand packet flow across OSI layers, stateful firewall rules, intrusion detection/prevention systems (Snort/Suricata), VPN tunneling protocols, and Wireshark traffic inspection.',
    tags: ['OSI Model', 'Firewalls', 'IDS/IPS', 'VPN', 'Network Monitoring', 'Network security course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 32,
    title: 'Android Starter: Kotlin Kickoff',
    slug: 'android-starter-kotlin-kickoff',
    category: CourseCategory.MOBILE_DEVELOPMENT,
    subcategory: 'Native App Development',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['UI Layouts', 'Intents', 'Jetpack Compose', 'Activities', 'Fragments'],
    targetAudience: 'Students wanting Android development',
    prerequisites: 'Basic programming knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Android + Kotlin Google ecosystem',
    suggestedKeyword: 'Kotlin Android course India',
    price: 3499,
    originalPrice: 6999,
    rating: 4.8,
    shortDescription: 'Android + Kotlin Google ecosystem. Build native Android apps with Kotlin and Jetpack Compose.',
    description: 'Start native Android development with modern Kotlin. Master Android Studio, declarative UI with Jetpack Compose, Activity lifecycles, Intent routing, Fragments, and material design components.',
    tags: ['UI Layouts', 'Intents', 'Jetpack Compose', 'Activities', 'Fragments', 'Android', 'Kotlin Android course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 33,
    title: 'Flutter Verse: Cross-Platform Apps',
    slug: 'flutter-verse-cross-platform-apps',
    category: CourseCategory.MOBILE_DEVELOPMENT,
    subcategory: 'Cross-platform',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Widgets', 'State Management', 'Firebase Integration', 'Platform Channels'],
    targetAudience: 'Mobile developers wanting cross-platform skills',
    prerequisites: 'Basic Dart or programming knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Cross-platform efficiency appeal',
    suggestedKeyword: 'Flutter app development course',
    price: 3999,
    originalPrice: 7999,
    rating: 4.9,
    shortDescription: 'Cross-platform efficiency appeal. Build multi-platform Flutter apps with Firebase integration.',
    description: 'Cross-platform Flutter application engineering. Learn clean UI layouts using custom widgets, state management approaches (Provider/Riverpod), Firebase Firestore integration, and platform method channels.',
    tags: ['Widgets', 'State Management', 'Firebase Integration', 'Platform Channels', 'Flutter', 'Flutter app development course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 34,
    title: 'React Native Rider',
    slug: 'react-native-rider',
    category: CourseCategory.MOBILE_DEVELOPMENT,
    subcategory: 'Cross-platform',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Navigation', 'Redux', 'Expo', 'Native Modules', 'Push Notifications'],
    targetAudience: 'JS developers wanting mobile skills',
    prerequisites: 'JavaScript + React basics',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'JS-to-mobile bridge; AppFoundry feeder',
    suggestedKeyword: 'React Native course India',
    price: 3999,
    originalPrice: 7999,
    rating: 4.8,
    shortDescription: 'JS-to-mobile bridge; AppFoundry feeder. Build native iOS & Android apps with React Native & Expo.',
    description: 'Use your React skills to build native mobile apps. Master Expo CLI, React Navigation, mobile device sensors, Redux Toolkit mobile state, offline storage, and push notifications.',
    tags: ['Navigation', 'Redux', 'Expo', 'Native Modules', 'Push Notifications', 'React Native', 'React Native course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 35,
    title: 'iOS Insights: Swift Basics',
    slug: 'ios-insights-swift-basics',
    category: CourseCategory.MOBILE_DEVELOPMENT,
    subcategory: 'Native App Development',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 22,
    lessonsCount: 18,
    keyTopics: ['Swift Syntax', 'Storyboards', 'Xcode', 'UIKit Basics', 'Auto Layout'],
    targetAudience: 'Apple ecosystem enthusiasts',
    prerequisites: 'Basic programming',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Premium Apple ecosystem niche',
    suggestedKeyword: 'Swift iOS basics course',
    price: 3499,
    originalPrice: 6999,
    rating: 4.8,
    shortDescription: 'Premium Apple ecosystem niche. Learn Swift syntax, Xcode environment, and Auto Layout.',
    description: 'Entry-level iOS engineering for Apple enthusiasts. Learn Swift language fundamentals, Xcode project setups, Storyboard visual design, UIKit interface controls, and Auto Layout constraints.',
    tags: ['Swift Syntax', 'Storyboards', 'Xcode', 'UIKit Basics', 'Auto Layout', 'iOS', 'Swift iOS basics course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 36,
    title: 'UI Essentials: Intro to UI Design',
    slug: 'ui-essentials-intro-to-ui-design',
    category: CourseCategory.DESIGN,
    subcategory: 'Experience & Design',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 16,
    lessonsCount: 12,
    keyTopics: ['Color Theory', 'Typography', 'Layout Principles', 'Visual Hierarchy'],
    targetAudience: 'Complete design beginners; non-CS students',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Design literacy for everyone',
    suggestedKeyword: 'UI Design basics course',
    price: 1999,
    originalPrice: 3999,
    rating: 4.8,
    shortDescription: 'Design literacy for everyone. Learn color palettes, typography scales, and visual hierarchy.',
    description: 'Build your aesthetic foundation for visual UI design. Master complementary color theory, font pairings, 8pt spatial layout grids, visual contrast, visual hierarchy, and iconography.',
    tags: ['Color Theory', 'Typography', 'Layout Principles', 'Visual Hierarchy', 'UI Design', 'UI Design basics course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 37,
    title: 'Figma Draw: Design to Prototype',
    slug: 'figma-draw-design-to-prototype',
    category: CourseCategory.DESIGN,
    subcategory: 'Tools & Software',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['Wireframes', 'Components', 'Prototypes', 'Design Systems Basics'],
    targetAudience: 'Students wanting production Figma skills',
    prerequisites: 'UI Essentials or basic design knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Industry standard design tool',
    suggestedKeyword: 'Figma course India',
    price: 3499,
    originalPrice: 6999,
    rating: 4.9,
    shortDescription: 'Industry standard design tool. Master Figma wireframing, reusable components, and interactive prototypes.',
    description: 'Hands-on UI design in Figma. Learn wireframing from scratch, building reusable master components, auto-layout responsiveness, and wiring up interactive clickable screen prototypes.',
    tags: ['Wireframes', 'Components', 'Prototypes', 'Design Systems', 'Figma', 'Figma course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 38,
    title: 'UX Impact: Journey Mapping',
    slug: 'ux-impact-journey-mapping',
    category: CourseCategory.DESIGN,
    subcategory: 'Experience & Design',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Empathy Maps', 'User Flows', 'Personas', 'Journey Maps', 'Card Sorting'],
    targetAudience: 'UX students and product thinkers',
    prerequisites: 'Basic UX awareness',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Research side UX; product thinking',
    suggestedKeyword: 'UX journey mapping course',
    price: 2999,
    originalPrice: 5999,
    rating: 4.8,
    shortDescription: 'Research side UX; product thinking. Master empathy mapping, user flows, and customer journey maps.',
    description: 'Transform user insights into seamless digital experiences. Learn qualitative empathy mapping, creating actionable user personas, mapping user journey funnels, and card sorting experiments.',
    tags: ['Empathy Maps', 'User Flows', 'Personas', 'Journey Maps', 'Card Sorting', 'UX', 'UX journey mapping course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 39,
    title: 'Design Systems Deep Dive',
    slug: 'design-systems-deep-dive',
    category: CourseCategory.DESIGN,
    subcategory: 'Advanced Design',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Design Tokens', 'Pattern Libraries', 'Component Architecture', 'Style Guides'],
    targetAudience: 'Advanced designers building scalable design systems',
    prerequisites: 'Figma Flow or intermediate design skills',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Enterprise design skill; system thinking',
    suggestedKeyword: 'Design systems course',
    price: 4499,
    originalPrice: 8999,
    rating: 4.9,
    shortDescription: 'Enterprise design skill; system thinking. Architect scalable design tokens, style guides, and libraries.',
    description: 'Enterprise design system architecture. Learn cross-platform design tokens (colors, spacing, typography), variant architectures in Figma, documentation governance, and design-to-code handoff.',
    tags: ['Design Tokens', 'Pattern Libraries', 'Component Architecture', 'Style Guides', 'Design Systems', 'Design systems course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 40,
    title: 'SDLC Simplified',
    slug: 'sdlc-simplified-course',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Process & Practices',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 10,
    lessonsCount: 8,
    keyTopics: ['Agile', 'Scrum', 'Waterfall', 'V-Model', 'Kanban', 'Sprint Planning'],
    targetAudience: 'All students wanting software process awareness',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Process foundations; pairs with any tech course',
    suggestedKeyword: 'SDLC Agile course',
    price: 999,
    originalPrice: 1999,
    rating: 4.8,
    shortDescription: 'Process foundations; pairs with any tech course. Understand Agile, Scrum, Waterfall, and Kanban.',
    description: 'Comprehensive software development lifecycle methodologies. Understand Waterfall, Agile, Scrum sprints, Kanban task boards, QA phases, release gates, and software deployment lifecycles.',
    tags: ['Agile', 'Scrum', 'Waterfall', 'V-Model', 'Kanban', 'Sprint Planning', 'SDLC', 'SDLC Agile course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 41,
    title: 'GitGuru: Version Control with Git',
    slug: 'gitguru-version-control-with-git',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Tools & Tech',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 15,
    lessonsCount: 12,
    keyTopics: ['Commits', 'Branches', 'GitHub', 'Collaboration', 'Conflict Resolution'],
    targetAudience: 'Everyone — foundational developer skill',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Universal prerequisite',
    suggestedKeyword: 'Git version control course',
    price: 1499,
    originalPrice: 2999,
    rating: 4.9,
    shortDescription: 'Universal prerequisite. Master Git commits, feature branching, pull requests, and merge conflicts.',
    description: 'Master practical Git command-line workflows. Learn staging commits, feature branching, remote tracking, GitHub pull request etiquette, rebasing, and resolving merge conflicts.',
    tags: ['Commits', 'Branches', 'GitHub', 'Collaboration', 'Conflict Resolution', 'Git', 'Git version control course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 42,
    title: 'Agile Pro: Jira & Team Collaboration',
    slug: 'agile-pro-jira-team-collaboration',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Process & Practices',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 22,
    lessonsCount: 18,
    keyTopics: ['Sprint Planning', 'Kanban Boards', 'Burndown Charts', 'Jira Workflows', 'Retrospectives'],
    targetAudience: 'Students working in team projects or internships',
    prerequisites: 'SDLC Simplified or team experience',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Tool-specific project management',
    suggestedKeyword: 'Jira Agile training course',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'Tool-specific project management. Master Jira issue tracking, sprint planning, and burndown charts.',
    description: 'Professional engineering project management with Atlassian Jira. Learn epics, user stories, story point estimation, sprint backlog grooming, Kanban boards, and tracking velocity burndown charts.',
    tags: ['Sprint Planning', 'Kanban Boards', 'Burndown Charts', 'Jira Workflows', 'Retrospectives', 'Jira', 'Jira Agile training course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 43,
    title: 'Design Patterns Unlocked',
    slug: 'design-patterns-unlocked',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Architecture',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Singleton', 'Factory', 'Observer', 'Strategy', 'Decorator', 'MVC', 'MVVM'],
    targetAudience: 'Intermediate developers wanting architecture skills',
    prerequisites: 'OOP proficiency in any language',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Code architecture; senior-dev positioning',
    suggestedKeyword: 'Design patterns course developers',
    price: 2999,
    originalPrice: 5999,
    rating: 4.9,
    shortDescription: 'Code architecture; senior-dev positioning. Master Creational, Structural, and Behavioral patterns.',
    description: 'Classic Gang-of-Four design patterns for robust, clean codebases. Master Creational (Singleton, Factory), Structural (Decorator, Adapter), Behavioral (Observer, Strategy), and architectural MVC/MVVM patterns.',
    tags: ['Singleton', 'Factory', 'Observer', 'Strategy', 'Decorator', 'MVC', 'MVVM', 'Design patterns course developers'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 44,
    title: 'System Design Starter',
    slug: 'system-design-starter-guide',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Architecture',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Scalability', 'Caching', 'DB Sharding', 'Load Balancing', 'Microservices', 'CAP Theorem'],
    targetAudience: 'Senior students targeting system design interviews',
    prerequisites: 'Strong programming + distributed systems basics',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'FAANG interview prep essential',
    suggestedKeyword: 'System design interview course',
    price: 4999,
    originalPrice: 9999,
    rating: 4.9,
    shortDescription: 'FAANG interview prep essential. Learn caching, database sharding, load balancing, and CAP theorem.',
    description: 'High-level architecture fundamentals for high-throughput software systems. Learn DNS routing, CDN caching, load balancers, database horizontal sharding, Redis caches, and distributed consistency trade-offs.',
    tags: ['Scalability', 'Caching', 'DB Sharding', 'Load Balancing', 'Microservices', 'CAP Theorem', 'System design interview course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 45,
    title: 'Project Forge: Real-world Internship Project',
    slug: 'project-forge-real-world-internship-project',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Internship Simulation',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Version Control', 'Real APIs', 'Agile Sprints', 'Code Reviews', 'Documentation'],
    targetAudience: 'Students wanting real-world work experience',
    prerequisites: 'At least one intermediate dev course completed',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Pre-internship simulation',
    suggestedKeyword: 'Real-world project internship',
    price: 3999,
    originalPrice: 7999,
    rating: 4.9,
    shortDescription: 'Pre-internship simulation. Build commercial features in simulated agile sprints with code reviews.',
    description: 'Simulated real-world internship project experience. Work within team sprints, implement third-party REST APIs, participate in pull request peer reviews, and deliver full technical documentation.',
    tags: ['Version Control', 'Real APIs', 'Agile Sprints', 'Code Reviews', 'Documentation', 'Real-world project internship'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 46,
    title: 'Capstone Connect',
    slug: 'capstone-connect-final-project',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Final Projects',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 40,
    lessonsCount: 30,
    keyTopics: ['Product Design', 'Team Collaboration', 'MVP', 'Deployment', 'Pitch Presentation'],
    targetAudience: 'Final-year students building portfolio capstones',
    prerequisites: 'Multiple intermediate dev courses completed',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Portfolio capstone; graduation project',
    suggestedKeyword: 'Capstone project course tech',
    price: 4999,
    originalPrice: 9999,
    rating: 4.9,
    shortDescription: 'Portfolio capstone; graduation project. Design, code, deploy, and pitch a complete MVP.',
    description: 'The crowning achievement of your coding journey. Form a multidisciplinary team to ideate, architect, build, deploy, and pitch a complete Minimum Viable Product (MVP) to industry mentors.',
    tags: ['Product Design', 'Team Collaboration', 'MVP', 'Deployment', 'Pitch Presentation', 'Capstone project course tech'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 47,
    title: 'ResumeReady: Portfolio & Resume Builder',
    slug: 'resumeready-portfolio-resume-builder',
    category: CourseCategory.BUSINESS,
    subcategory: 'Career Building',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 12,
    lessonsCount: 10,
    keyTopics: ['Resume Formats', 'GitHub Portfolio', 'LinkedIn Optimization', 'Personal Branding'],
    targetAudience: 'All students — especially pre-placement',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Immediate career ROI; quick win',
    suggestedKeyword: 'Resume portfolio builder course',
    price: 1499,
    originalPrice: 2999,
    rating: 4.9,
    shortDescription: 'Immediate career ROI; quick win. Craft ATS resumes, optimize LinkedIn, and brand your GitHub.',
    description: 'Get hired faster with high-impact job search collateral. Learn ATS-tested resume formatting, writing quantifiable bullet points, optimizing LinkedIn search tags, and presenting GitHub projects.',
    tags: ['Resume Formats', 'GitHub Portfolio', 'LinkedIn Optimization', 'Personal Branding', 'Career', 'Resume portfolio builder course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 48,
    title: 'InterviewCrack: Mock Interview Series',
    slug: 'interviewcrack-mock-interview-series',
    category: CourseCategory.BUSINESS,
    subcategory: 'Interview Prep',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Behavioral Questions', 'Coding Round', 'HR Round', 'Mock Sessions', 'Feedback'],
    targetAudience: 'Placement-season students',
    prerequisites: 'AlgoCore + basic system design',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Direct placement impact',
    suggestedKeyword: 'Mock interview preparation course',
    price: 2999,
    originalPrice: 5999,
    rating: 4.9,
    shortDescription: 'Direct placement impact. Practice live technical and HR mock interviews with detailed feedback.',
    description: 'Intensive mock interview simulations. Practice live technical whiteboarding, problem breakdown, STAR behavioral responses, and HR cultural fit interviews with personalized feedback.',
    tags: ['Behavioral Questions', 'Coding Round', 'HR Round', 'Mock Sessions', 'Feedback', 'Mock interview preparation course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 49,
    title: 'SpeakTech: Communication for Engineers',
    slug: 'speaktech-communication-for-engineers',
    category: CourseCategory.BUSINESS,
    subcategory: 'Soft Skills',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 15,
    lessonsCount: 12,
    keyTopics: ['Presentations', 'Meetings', 'Feedback', 'Email Etiquette', 'Pitching Ideas'],
    targetAudience: 'All students, especially introverts in tech',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Soft-skills differentiator',
    suggestedKeyword: 'Communication skills engineers',
    price: 1999,
    originalPrice: 3999,
    rating: 4.8,
    shortDescription: 'Soft-skills differentiator. Master technical presentations, workplace meetings, and clear emails.',
    description: 'Transform your professional communication impact. Learn technical presentation delivery, active participation in engineering meetings, constructive feedback exchange, and persuasive written communications.',
    tags: ['Presentations', 'Meetings', 'Feedback', 'Email Etiquette', 'Pitching Ideas', 'Communication skills engineers'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 50,
    title: 'WordPress Starter',
    slug: 'wordpress-starter-cms-setup',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'CMS',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 16,
    lessonsCount: 12,
    keyTopics: ['WordPress Setup', 'Customization', 'SEO', 'Hosting', 'Elementor Basics'],
    targetAudience: 'Non-coders, freelancers, small biz owners',
    prerequisites: 'Basic internet literacy',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Freelancer pipeline; quick monetization',
    suggestedKeyword: 'WordPress setup course',
    price: 1999,
    originalPrice: 3999,
    rating: 4.8,
    shortDescription: 'Freelancer pipeline; quick monetization. Setup and design client websites with WordPress & Elementor.',
    description: 'Launch websites quickly using WordPress. Learn hosting management, theme customization, Elementor page builder basics, contact form integrations, and essential on-page SEO techniques.',
    tags: ['WordPress Setup', 'Customization', 'SEO', 'Hosting', 'Elementor Basics', 'WordPress setup course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 51,
    title: 'Shopify Launchpad',
    slug: 'shopify-launchpad-ecommerce-store',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'E-Commerce',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 16,
    lessonsCount: 12,
    keyTopics: ['Product Listing', 'Checkout', 'Themes', 'App Integrations', 'Analytics'],
    targetAudience: 'Anyone wanting an e-commerce shop',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Quick store launch',
    suggestedKeyword: 'Shopify setup course',
    price: 1999,
    originalPrice: 3999,
    rating: 4.8,
    shortDescription: 'Quick store launch. Build and launch a complete e-commerce storefront on Shopify.',
    description: 'Launch an online store in days on Shopify. Learn store settings, theme adjustments, catalog and variant setup, payment gateway configuration, and essential Shopify app extensions.',
    tags: ['Product Listing', 'Checkout', 'Themes', 'App Integrations', 'Analytics', 'Shopify setup course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 52,
    title: 'Magento Mastery',
    slug: 'magento-mastery-ecommerce',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Magento',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Architecture', 'Modules', 'Custom Development', 'Themes', 'Multi-store'],
    targetAudience: 'Enterprise eCommerce developers',
    prerequisites: 'Basic PHP/e-commerce understanding',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Enterprise eCommerce niche',
    suggestedKeyword: 'Magento course India',
    price: 4499,
    originalPrice: 8999,
    rating: 4.7,
    shortDescription: 'Enterprise eCommerce niche. Master Adobe Commerce/Magento modules, themes, and multi-stores.',
    description: 'Enterprise e-commerce development with Magento / Adobe Commerce. Learn directory structure, dependency injection, custom module development, layout XML, and multi-store management.',
    tags: ['Architecture', 'Modules', 'Custom Development', 'Themes', 'Multi-store', 'Magento', 'Magento course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 53,
    title: 'BigCommerce Bootcamp',
    slug: 'bigcommerce-bootcamp-training',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'BigCommerce',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 22,
    lessonsCount: 18,
    keyTopics: ['Store Setup', 'Inventory Management', 'Checkout', 'Multi-channel Selling'],
    targetAudience: 'Mid-market eCommerce operators',
    prerequisites: 'Basic eCommerce understanding',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Alternative to Shopify; enterprise scale',
    suggestedKeyword: 'BigCommerce training course',
    price: 3499,
    originalPrice: 6999,
    rating: 4.8,
    shortDescription: 'Alternative to Shopify; enterprise scale. Learn BigCommerce store management and multi-channel sales.',
    description: 'Master SaaS e-commerce on BigCommerce. Learn store customization, B2B and B2C product catalogs, inventory management, custom checkout flows, and multi-channel marketplace integrations.',
    tags: ['Store Setup', 'Inventory Management', 'Checkout', 'Multi-channel Selling', 'BigCommerce', 'BigCommerce training course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 54,
    title: 'Headless CMS Odyssey for CMS',
    slug: 'headless-cms-odyssey-modern-jamstack',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Headless CMS',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Content Modeling', 'REST API', 'React Frontend', 'Next.js Integration'],
    targetAudience: 'Developers wanting modern headless architecture',
    prerequisites: 'React + Node.js proficiency',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Modern JAMstack architecture',
    suggestedKeyword: 'Headless CMS course',
    price: 2999,
    originalPrice: 5999,
    rating: 4.9,
    shortDescription: 'Modern JAMstack architecture. Decouple CMS backends with REST APIs and Next.js frontends.',
    description: 'Modern content architecture with Headless CMS backends. Learn content modeling, structured data types, API consumption via GraphQL and REST, and rendering dynamic pages with Next.js.',
    tags: ['Content Modeling', 'REST API', 'React Frontend', 'Next.js Integration', 'Headless CMS', 'Headless CMS course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 55,
    title: 'PeopleCraft: HR & People Operations',
    slug: 'peoplecraft-hr-people-operations',
    category: CourseCategory.BUSINESS,
    subcategory: 'HR Skills',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['HR Basics', 'Recruitment Process', 'People Management', 'HRIS Tools'],
    targetAudience: 'Non-tech students; HR-curious candidates',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes',
    funnelTier: 'Tier 2',
    marketingAngle: 'Non-tech diversification',
    suggestedKeyword: 'HR people operations course',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'Non-tech diversification. Learn modern HR operations, recruitment pipelines, and HRIS software.',
    description: 'Essential human resource management and people operations. Learn end-to-end recruitment lifecycle sourcing, interview coordination, employee onboarding, performance appraisals, and modern HRIS tools.',
    tags: ['HR Basics', 'Recruitment Process', 'People Management', 'HRIS Tools', 'People Operations', 'HR people operations course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
];

async function seedCoursesSet2() {
  try {
    const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/growthcraft';
    await mongoose.connect(MONGODB_URI);
    logger.info('Connected to MongoDB');

    // 1. Initialize / Update CourseConfig for categories and levels
    const configDefaults = [
      {
        key: 'categories',
        values: [
          CourseCategory.PROGRAMMING,
          CourseCategory.WEB_DEVELOPMENT,
          CourseCategory.DATA_SCIENCE,
          CourseCategory.AI_ML,
          CourseCategory.DEVOPS,
          CourseCategory.CLOUD_COMPUTING,
          CourseCategory.CYBERSECURITY,
          CourseCategory.MOBILE_DEVELOPMENT,
          CourseCategory.DESIGN,
          CourseCategory.BUSINESS,
          CourseCategory.OTHER,
        ],
        isActive: true,
      },
      {
        key: 'difficultyLevels',
        values: ['Beginner', 'Intermediate', 'Advanced', 'Expert'],
        isActive: true,
      },
      {
        key: 'courseTypes',
        values: ['Course', 'Bootcamp'],
        isActive: true,
      },
    ];

    for (const config of configDefaults) {
      await CourseConfig.findOneAndUpdate(
        { key: config.key },
        { values: config.values, isActive: config.isActive },
        { new: true, upsert: true }
      ).exec();
    }
    logger.info('✓ Course configurations verified');

    // 2. Upsert each course from Courses - Set 2
    let inserted = 0;
    let updated = 0;

    for (const item of coursesSet2Data) {
      const existing = await Course.findOne({ slug: item.slug }).exec();

      const docData = {
        title: item.title,
        slug: item.slug,
        shortDescription: item.shortDescription,
        description: item.description,
        category: item.category,
        level: item.level,
        difficultyLevel: item.difficultyLevel,
        duration: item.duration,
        totalHours: item.duration,
        lessonsCount: item.lessonsCount,
        price: item.price,
        originalPrice: item.originalPrice,
        rating: item.rating,
        tags: item.tags,
        instructor: item.instructor,
        instructorId: item.instructor.name,
        enrollmentCount: Math.floor(Math.random() * 250) + 100,
        isActive: true,
        isPublished: true,
        isDraft: false,
        publishedAt: new Date('2024-02-01T00:00:00.000Z'),
        type: 'Course',
      };

      await Course.findOneAndUpdate(
        { slug: item.slug },
        { $set: docData },
        { new: true, upsert: true, runValidators: true }
      ).exec();

      if (existing) {
        updated++;
      } else {
        inserted++;
      }
    }

    logger.info(`✓ Seeded ${coursesSet2Data.length} courses from Courses - Set 2 (${inserted} created, ${updated} updated)`);

    // 3. Print verification breakdown
    const totalCourses = await Course.countDocuments({ isPublished: true, isActive: true });
    console.log('\n=============================================');
    console.log('✓ Courses - Set 2 Seeding Complete');
    console.log(`Total Active & Published Courses in DB: ${totalCourses}`);
    console.log('=============================================');

    const byCategory = await Course.aggregate([
      { $match: { isPublished: true, isActive: true } },
      { $group: { _id: '$category', count: { $sum: 1 } } },
      { $sort: { count: -1 } },
    ]);

    console.log('\nBreakdown by Category:');
    byCategory.forEach(cat => {
      console.log(`  • ${cat._id}: ${cat.count} courses`);
    });

    const byLevel = await Course.aggregate([
      { $match: { isPublished: true, isActive: true } },
      { $group: { _id: '$difficultyLevel', count: { $sum: 1 } } },
      { $sort: { count: -1 } },
    ]);

    console.log('\nBreakdown by Level:');
    byLevel.forEach(lvl => {
      console.log(`  • ${lvl._id}: ${lvl.count} courses`);
    });

    console.log('\n=============================================\n');

    process.exit(0);
  } catch (error) {
    logger.error('Error seeding Courses - Set 2:', error);
    process.exit(1);
  }
}

// Run seeder
seedCoursesSet2();
