import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { Course, CourseCategory, CourseLevel } from '../src/database/models/Course.model';
import { CourseConfig } from '../src/database/models/CourseConfig.model';

dotenv.config({ path: path.join(__dirname, '../.env') });

const logger = {
  info: (msg: string) => console.log(`[INFO] ${msg}`),
  warn: (msg: string) => console.warn(`[WARN] ${msg}`),
  error: (msg: string, error?: any) => console.error(`[ERROR] ${msg}`, error || ''),
};

export interface CourseSet1Item {
  sNo: number;
  title: string;
  slug: string;
  category: CourseCategory;
  subcategory: string;
  level: CourseLevel;
  difficultyLevel: string;
  duration: number;
  lessonsCount: number;
  keyTopics: string[];
  targetAudience: string;
  prerequisites: string;
  deliveryMode: string;
  certificate: string;
  funnelTier: string;
  marketingAngle: string;
  suggestedKeyword: string;
  price: number;
  originalPrice: number;
  rating: number;
  shortDescription: string;
  description: string;
  tags: string[];
  instructor: {
    name: string;
    avatar?: string;
  };
}

export const coursesSet1Data: CourseSet1Item[] = [
  {
    sNo: 1,
    title: 'CodeCraft: Python 101',
    slug: 'codecraft-python-101',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Core Programming',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['Python Basics', 'Data Types', 'Loops', 'Functions', 'File I/O'],
    targetAudience: 'First-year students, complete beginners',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Entry-level hook; first course for any coding track',
    suggestedKeyword: 'Learn Python Guwahati',
    price: 2499,
    originalPrice: 4999,
    rating: 4.9,
    shortDescription: 'Entry-level hook; first course for any coding track. Master Python basics, loops, and functions.',
    description: 'Learn Python from the ground up with interactive on-campus sessions. Master fundamental syntax, variables, data structures, conditional logic, loops, functions, and file I/O operations tailored for complete beginners.',
    tags: ['Python', 'Core Programming', 'Data Types', 'Loops', 'Functions', 'File I/O', 'Learn Python Guwahati'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 2,
    title: 'CodeCraft: Java, C++, C# Quad Core',
    slug: 'codecraft-java-cpp-csharp-quad-core',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Core Programming',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 50,
    lessonsCount: 35,
    keyTopics: ['Java', 'C++', 'C#', 'OOP Principles', 'Error Handling', 'Multithreading Basics'],
    targetAudience: 'Students with basic programming knowledge; multi-language exposure seekers',
    prerequisites: 'CodeCraft or equivalent python/programming basics',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Multi-language appeal; competitive exam relevance',
    suggestedKeyword: 'Java C++ crash course India',
    price: 4999,
    originalPrice: 8999,
    rating: 4.8,
    shortDescription: 'Multi-language appeal; competitive exam relevance. Master Java, C++, C#, and OOP principles.',
    description: 'Master core object-oriented programming paradigms across Java, C++, and C#. Covers memory management, class hierarchies, interfaces, robust error handling, collections, and foundational multithreading.',
    tags: ['Java', 'C++', 'C#', 'OOP Principles', 'Error Handling', 'Multithreading', 'Java C++ crash course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 3,
    title: 'AlgoCore: Mastering DSA',
    slug: 'algocore-mastering-dsa',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Core Programming',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 50,
    lessonsCount: 40,
    keyTopics: ['Arrays', 'Linked Lists', 'Trees', 'Graphs', 'Sorting', 'Searching', 'Recursion'],
    targetAudience: 'Students aiming for tech placements; competitive coding aspirants',
    prerequisites: 'Programming in any language',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Placement essential; intro/warm-up for AlgoPro',
    suggestedKeyword: 'DSA course for placements',
    price: 4999,
    originalPrice: 9999,
    rating: 4.9,
    shortDescription: 'Placement essential; intro/warm-up for AlgoPro. Master arrays, trees, graphs, and recursion.',
    description: 'Comprehensive Data Structures and Algorithms curriculum designed to ace campus placement technical rounds. Covers asymptotic analysis, arrays, linked lists, stacks, queues, trees, graphs, sorting, and recursion patterns.',
    tags: ['DSA', 'Arrays', 'Linked Lists', 'Trees', 'Graphs', 'Sorting', 'Recursion', 'DSA course for placements'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 4,
    title: 'CP Sprint: Competitive Coding Bootcamp',
    slug: 'cp-sprint-competitive-coding-bootcamp',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Competitive Programming',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 40,
    lessonsCount: 30,
    keyTopics: ['Advanced Algorithms', 'Segment Trees', 'Trie', 'DP', 'Advanced Graph Theory', 'Math/Number Theory'],
    targetAudience: 'Advanced coders targeting competitive coding, hackathons, and tier-1 companies',
    prerequisites: 'AlgoCore or strong DSA foundation',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Elite-level profile building; leaderboard culture',
    suggestedKeyword: 'Competitive coding training India',
    price: 5499,
    originalPrice: 10999,
    rating: 4.9,
    shortDescription: 'Elite-level profile building; leaderboard culture. Master segment trees, dynamic programming, and graphs.',
    description: 'Intensive competitive coding program for top-tier contests (Codeforces, LeetCode, CodeChef) and FAANG coding screens. Focuses on advanced DP, segment trees, Trie structures, topological sort, shortest paths, and number theory.',
    tags: ['Competitive Programming', 'Segment Trees', 'Trie', 'Dynamic Programming', 'Graph Theory', 'Number Theory', 'Competitive coding training India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 5,
    title: 'WebStart: HTML to DOM',
    slug: 'webstart-html-to-dom',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Frontend Development',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['HTML5', 'CSS3', 'DOM Manipulation', 'Responsive Design', 'Flexbox', 'Grid'],
    targetAudience: 'Complete beginners; first-year students wanting to build websites',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'First web course; quick visual results + high engagement',
    suggestedKeyword: 'Learn HTML CSS Guwahati',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'First web course; quick visual results + high engagement. Build modern responsive websites from scratch.',
    description: 'Build your first real-world website. Learn semantic HTML5 markup, modern CSS3 styling, responsive layouts using Flexbox and CSS Grid, and dynamic interactivity via browser DOM manipulation with JavaScript.',
    tags: ['HTML5', 'CSS3', 'DOM Manipulation', 'Responsive Design', 'Flexbox', 'Grid', 'Learn HTML CSS Guwahati'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 6,
    title: 'React Ready: Build with Components',
    slug: 'react-ready-build-with-components',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Frontend Development',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 25,
    keyTopics: ['React.js', 'JSX', 'Props', 'State', 'Hooks', 'React Router', 'Component Architecture'],
    targetAudience: 'Students with basic web knowledge wanting to build modern web apps',
    prerequisites: 'WebStart or HTML/CSS/JS proficiency',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Most in-demand frontend framework; cornerstone workshop',
    suggestedKeyword: 'React.js training course India',
    price: 3999,
    originalPrice: 7999,
    rating: 4.9,
    shortDescription: 'Most in-demand frontend framework; cornerstone workshop. Master React.js, Hooks, and Router.',
    description: 'Master component-driven frontend architecture with React.js. Learn JSX syntax, state and props management, essential React Hooks (useState, useEffect, useMemo, useCallback), React Router, and modular design patterns.',
    tags: ['React.js', 'JSX', 'Hooks', 'React Router', 'Component Architecture', 'Frontend', 'React.js training course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 7,
    title: 'VueVersa: Vue.js Mastery',
    slug: 'vueversa-vuejs-mastery',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Frontend Development',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 25,
    keyTopics: ['Vue CLI', 'Vuex', 'Vue Router', 'SSR', 'Composition API', 'Pinia'],
    targetAudience: 'Developers wanting Vue.js expertise; alternative to React',
    prerequisites: 'React Ready or strong JS experience',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Niche framework; enterprise demand',
    suggestedKeyword: 'Vuejs course India',
    price: 3999,
    originalPrice: 7999,
    rating: 4.7,
    shortDescription: 'Niche framework; enterprise demand. Master Vue 3, Composition API, Pinia, and Vue Router.',
    description: 'Explore the elegance of Vue.js. Master Vue 3 Composition API, reactive state management with Pinia, single-file components (SFC), routing with Vue Router, and server-side rendering concepts.',
    tags: ['Vue.js', 'Vue Router', 'Pinia', 'Composition API', 'Vue CLI', 'Frontend', 'Vuejs course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 8,
    title: 'BackendBuilder: API Node.js',
    slug: 'backendbuilder-api-nodejs',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Backend Development',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 35,
    lessonsCount: 28,
    keyTopics: ['Node.js', 'Express.js', 'REST APIs', 'JSON', 'Authentication', 'Middleware'],
    targetAudience: 'Students ready to move from frontend to backend',
    prerequisites: 'WebStart or JS proficiency',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Backend unlock; pairs well with WebStart',
    suggestedKeyword: 'Nodejs Express backend course',
    price: 4499,
    originalPrice: 8499,
    rating: 4.8,
    shortDescription: 'Backend unlock; pairs well with WebStart. Build fast, secure REST APIs with Node.js and Express.',
    description: 'Transition into server-side web engineering. Learn Node.js asynchronous event loop, Express.js architecture, custom middleware, RESTful API contract design, JWT authentication, and database connectivity.',
    tags: ['Node.js', 'Express.js', 'REST APIs', 'JSON', 'Authentication', 'Middleware', 'Nodejs Express backend course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 9,
    title: 'Django Pro: Web Apps with Python',
    slug: 'django-pro-web-apps-with-python',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Backend Development',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 35,
    lessonsCount: 28,
    keyTopics: ['Django Framework', 'Models', 'Admin', 'ORM', 'Templates', 'Forms', 'Authentication'],
    targetAudience: 'Students already with basic Python wanting web backend skills',
    prerequisites: 'CodeCraft or Python proficiency',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Python developers web on-ramp; data science adjacent backend',
    suggestedKeyword: 'Django web development learning',
    price: 4499,
    originalPrice: 8499,
    rating: 4.8,
    shortDescription: 'Python developers web on-ramp; data science adjacent backend. Master Django models, ORM, and auth.',
    description: 'Build batteries-included web backends with Django and Python. Learn Django MVT architecture, model relationships, database migrations, Django ORM querying, admin site customization, forms, and user authentication.',
    tags: ['Django', 'Python', 'ORM', 'Models', 'Templates', 'Authentication', 'Django web development learning'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 10,
    title: 'FullStack Fusion: MERN Track',
    slug: 'fullstack-fusion-mern-track',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Full-Stack Tracks',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 60,
    lessonsCount: 45,
    keyTopics: ['MongoDB', 'Express.js', 'React.js', 'Node.js', 'MERN Integration', 'REST API', 'Full-Stack Deployment'],
    targetAudience: 'Students aiming for full-stack developer roles',
    prerequisites: 'React Ready + BackendBuilder or equivalent full-stack readiness',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Flagship course; direct pipeline into MERN Hackathon program',
    suggestedKeyword: 'MERN stack full course Assam',
    price: 6999,
    originalPrice: 13999,
    rating: 4.9,
    shortDescription: 'Flagship course; direct pipeline into MERN Hackathon program. Connect MongoDB, Express, React, and Node.',
    description: 'The definitive full-stack development experience. Unify MongoDB, Express.js, React.js, and Node.js to create production-ready web applications with full authentication, state synchronization, CRUD APIs, and cloud deployment.',
    tags: ['MERN', 'MongoDB', 'Express.js', 'React.js', 'Node.js', 'Full-Stack', 'Deployment', 'MERN stack full course Assam'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 11,
    title: 'DataSprint: Python for Data Analysis',
    slug: 'datasprint-python-for-data-analysis',
    category: CourseCategory.DATA_SCIENCE,
    subcategory: 'Advanced Tracks',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Python for Data Analysis', 'Pandas', 'NumPy', 'Data Cleaning', 'EDA'],
    targetAudience: 'Students with basic Python, curious about data analytics',
    prerequisites: 'CodeCraft or basic Python knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Data analytics gateway; non-CS math/stats students welcome',
    suggestedKeyword: 'Python data analytics course India',
    price: 3499,
    originalPrice: 6999,
    rating: 4.8,
    shortDescription: 'Data analytics gateway; non-CS math/stats students welcome. Master Pandas, NumPy, and EDA.',
    description: 'Turn raw numbers into actionable insight. Master NumPy array operations, Pandas DataFrame manipulation, data sanitization, handling missing values, statistical analysis, and Exploratory Data Analysis (EDA) visualizations.',
    tags: ['Python', 'Data Analytics', 'Pandas', 'NumPy', 'Data Cleaning', 'EDA', 'Python data analytics course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 12,
    title: 'ML Launchpad: Machine Learning Essentials',
    slug: 'ml-launchpad-machine-learning-essentials',
    category: CourseCategory.AI_ML,
    subcategory: 'Advanced Tracks',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 50,
    lessonsCount: 36,
    keyTopics: ['Supervised Learning', 'Scikit-learn', 'Linear/Logistic Regression', 'Model Evaluation'],
    targetAudience: 'Students from data/science background moving to ML tracks',
    prerequisites: 'DataSprint or Python + basic statistics',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'High demand emerging field; research appeal',
    suggestedKeyword: 'Machine learning course Assam',
    price: 5499,
    originalPrice: 10999,
    rating: 4.9,
    shortDescription: 'High demand emerging field; research appeal. Master Scikit-learn, regression, and model evaluation.',
    description: 'Learn foundational applied machine learning. Covers supervised learning algorithms, linear and logistic regression, decision trees, random forests, feature scaling, model validation techniques, and Scikit-learn pipelines.',
    tags: ['Machine Learning', 'Scikit-learn', 'Regression', 'Classification', 'Model Evaluation', 'AI', 'Machine learning course Assam'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 13,
    title: 'AI & You: Build with GenAI',
    slug: 'ai-and-you-build-with-genai',
    category: CourseCategory.AI_ML,
    subcategory: 'Advanced Tracks',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 50,
    lessonsCount: 36,
    keyTopics: ['LLMs', 'LangChain', 'OpenAI API', 'Prompt Engineering', 'RAG', 'Embeddings'],
    targetAudience: 'Tech-savvy students wanting to build cutting-edge AI applications',
    prerequisites: 'ML Launchpad or strong Python + API experience',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'HOT CATEGORY — high search volume, high enrollment',
    suggestedKeyword: 'GenAI LangChain course India',
    price: 6499,
    originalPrice: 12999,
    rating: 4.9,
    shortDescription: 'HOT CATEGORY — high search volume, high enrollment. Build AI apps with LLMs, LangChain, and RAG.',
    description: 'Build modern Generative AI applications. Learn prompt engineering, OpenAI APIs, LangChain agents and chains, vector embeddings, vector databases (Pinecone/Chroma), and Retrieval-Augmented Generation (RAG) pipelines.',
    tags: ['GenAI', 'LLMs', 'LangChain', 'OpenAI', 'Prompt Engineering', 'RAG', 'Embeddings', 'GenAI LangChain course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 14,
    title: 'Analytics Guru: Visualize Everything',
    slug: 'analytics-guru-visualize-everything',
    category: CourseCategory.DATA_SCIENCE,
    subcategory: 'Advanced Tracks',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Tableau', 'Power BI', 'SQL for Analytics', 'Dashboards', 'Business KPIs'],
    targetAudience: 'Non-CS / analytics track; non-coders wanting data skills',
    prerequisites: 'Basic data/Excel familiarity',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Non-coder appeal; recruiters visible skills',
    suggestedKeyword: 'Power BI Tableau training',
    price: 3999,
    originalPrice: 7999,
    rating: 4.8,
    shortDescription: 'Non-coder appeal; recruiters visible skills. Master Power BI, Tableau, SQL, and interactive dashboards.',
    description: 'Master modern business intelligence and data visualization. Write analytical SQL queries to extract data, build interactive dashboards in Power BI and Tableau, track core business KPIs, and deliver boardroom-ready reports.',
    tags: ['Tableau', 'Power BI', 'SQL for Analytics', 'Dashboards', 'Business KPIs', 'Data Visualization', 'Power BI Tableau training'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 15,
    title: 'DevOps Jumpstart',
    slug: 'devops-jumpstart',
    category: CourseCategory.DEVOPS,
    subcategory: 'DevOps Foundations',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['Linux Basics', 'Bash Scripting', 'Git', 'CI/CD Concepts'],
    targetAudience: 'Students wanting a fast introduction to DevOps & cloud systems',
    prerequisites: 'Basic command-line familiarity',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Growing demand; infrastructure literacy',
    suggestedKeyword: 'DevOps beginner course India',
    price: 2999,
    originalPrice: 5999,
    rating: 4.8,
    shortDescription: 'Growing demand; infrastructure literacy. Learn Linux fundamentals, Bash scripting, and CI/CD pipelines.',
    description: 'Accelerate into modern DevOps culture and toolchains. Learn Linux file permissions, process management, shell scripting with Bash, Git versioning workflows, and foundational continuous integration concepts.',
    tags: ['Linux Basics', 'Bash Scripting', 'Git', 'CI/CD', 'DevOps', 'Infrastructure', 'DevOps beginner course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 16,
    title: 'CloudShift: AWS & Azure Foundations',
    slug: 'cloudshift-aws-azure-foundations',
    category: CourseCategory.CLOUD_COMPUTING,
    subcategory: 'DevOps Foundations',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 40,
    lessonsCount: 30,
    keyTopics: ['AWS EC2', 'S3', 'IAM', 'GCP Intro', 'Cloud Fundamentals', 'Serverless Basics'],
    targetAudience: 'Students preparing for cloud certifications / DevOps track',
    prerequisites: 'CloudShift or strong Linux fundamentals',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Cloud cert prep angle; multi-cloud versatility',
    suggestedKeyword: 'AWS Azure cloud training Guwahati',
    price: 4999,
    originalPrice: 9999,
    rating: 4.8,
    shortDescription: 'Cloud cert prep angle; multi-cloud versatility. Master AWS EC2, S3, IAM, Azure, and serverless.',
    description: 'Learn multi-cloud architecture and administration. Master AWS core services (EC2, S3, VPC, IAM), Azure cloud primitives, IAM role configuration, and serverless functions (AWS Lambda) for scalable deployments.',
    tags: ['AWS EC2', 'S3', 'IAM', 'Cloud Fundamentals', 'Serverless', 'Azure', 'AWS Azure cloud training Guwahati'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 17,
    title: 'DockerCraft: Containers and Orchestration',
    slug: 'dockercraft-containers-and-orchestration',
    category: CourseCategory.DEVOPS,
    subcategory: 'Containers & Orchestration',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 40,
    lessonsCount: 30,
    keyTopics: ['Docker Compose', 'Kubernetes', 'Helm', 'Microservices', 'Containerization'],
    targetAudience: 'Students targeting cloud engineering & modern infrastructure roles',
    prerequisites: 'CloudShift or basic Linux + Docker knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'DevOps boom cornerstone; Kubernetes demand',
    suggestedKeyword: 'Docker Kubernetes course Guwahati',
    price: 5499,
    originalPrice: 10999,
    rating: 4.9,
    shortDescription: 'DevOps boom cornerstone; Kubernetes demand. Master Docker Compose, Kubernetes clusters, and Helm.',
    description: 'Industry-standard container engineering. Learn Dockerfile optimization, multi-container orchestration with Docker Compose, Kubernetes architecture, Pods, Deployments, Services, Ingress, and Helm charts.',
    tags: ['Docker Compose', 'Kubernetes', 'Helm', 'Microservices', 'Containerization', 'DevOps', 'Docker Kubernetes course Guwahati'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 18,
    title: 'CyberShield: Fundamentals of Cybersecurity',
    slug: 'cybershield-fundamentals-of-cybersecurity',
    category: CourseCategory.CYBERSECURITY,
    subcategory: 'Fundamentals',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 24,
    lessonsCount: 20,
    keyTopics: ['OWASP Top 10', 'Network Security', 'Ethical Hacking Basics', 'Security Policies'],
    targetAudience: 'Students interested in cyber roles; non-technical / IT/CS background helpful',
    prerequisites: 'Any background; basic networking helpful',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'High-interest topic; cybersecurity cert pipeline',
    suggestedKeyword: 'Ethical hacking basics Guwahati',
    price: 2999,
    originalPrice: 5999,
    rating: 4.8,
    shortDescription: 'High-interest topic; cybersecurity cert pipeline. Learn OWASP Top 10, network security, and defense.',
    description: 'Essential cybersecurity and ethical hacking foundations. Understand network scanning, packet analysis, defense-in-depth, OWASP Top 10 web vulnerabilities, cryptography principles, and organizational security policies.',
    tags: ['OWASP Top 10', 'Network Security', 'Ethical Hacking', 'Security Policies', 'Cybersecurity', 'Ethical hacking basics Guwahati'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 19,
    title: 'HackNest: Bug Bounty & CTF Lab',
    slug: 'hacknest-bug-bounty-ctf-lab',
    category: CourseCategory.CYBERSECURITY,
    subcategory: 'CTF & Bug Bounty',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 35,
    lessonsCount: 28,
    keyTopics: ['CTF Challenges', 'Burp Suite', 'Web App Pentesting', 'Exploit Writing', 'Remediation'],
    targetAudience: 'Students wanting hands-on bug bounty / ethical hacking skills',
    prerequisites: 'CyberShield or strong networking background',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Gamified/hands-on positioning; bug bounty earnings hook',
    suggestedKeyword: 'Bug bounty training India',
    price: 4999,
    originalPrice: 9999,
    rating: 4.9,
    shortDescription: 'Gamified/hands-on positioning; bug bounty earnings hook. Master Burp Suite, pentesting, and CTFs.',
    description: 'Hands-on practical security auditing. Work through Capture The Flag (CTF) challenges, master Burp Suite proxy interception, test for SQLi, XSS, CSRF, IDOR, write proof-of-concept exploits, and document remediation reports.',
    tags: ['CTF Challenges', 'Burp Suite', 'Web App Pentesting', 'Exploit Writing', 'Remediation', 'Bug Bounty', 'Bug bounty training India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 20,
    title: 'AppStarter: Mobile Dev with Flutter',
    slug: 'appstarter-mobile-dev-with-flutter',
    category: CourseCategory.MOBILE_DEVELOPMENT,
    subcategory: 'Native & Cross Platform',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 30,
    lessonsCount: 25,
    keyTopics: ['Dart', 'Flutter Widgets', 'Layouts', 'Navigation', 'State Management', 'Firebase'],
    targetAudience: 'Students wanting to build cross-platform mobile apps',
    prerequisites: 'Basic programming knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Cross-platform appeal; quick app building showcase',
    suggestedKeyword: 'Flutter mobile app course India',
    price: 3999,
    originalPrice: 7999,
    rating: 4.8,
    shortDescription: 'Cross-platform appeal; quick app building showcase. Build iOS & Android apps with Flutter and Firebase.',
    description: 'Create multi-platform mobile applications from a unified codebase. Learn Dart language fundamentals, Flutter widget tree composition, state management, screen navigation, device hardware access, and Firebase backend integration.',
    tags: ['Dart', 'Flutter', 'Layouts', 'Navigation', 'State Management', 'Firebase', 'Mobile Dev', 'Flutter mobile app course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 21,
    title: 'iOS Insight: Swift Essentials',
    slug: 'ios-insight-swift-essentials',
    category: CourseCategory.MOBILE_DEVELOPMENT,
    subcategory: 'Native & Cross Platform',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 25,
    keyTopics: ['Swift Language', 'UIKit', 'SwiftUI', 'Architecture Patterns', 'Core Data'],
    targetAudience: 'Students interested in Apple ecosystem development',
    prerequisites: 'Basic OOP knowledge; Mac required for development',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Niche & premium; Apple ecosystem demand',
    suggestedKeyword: 'Swift iOS development course',
    price: 4499,
    originalPrice: 8999,
    rating: 4.8,
    shortDescription: 'Niche & premium; Apple ecosystem demand. Master Swift, SwiftUI, UIKit, and Core Data.',
    description: 'Native iOS engineering on the Apple platform. Learn Swift syntax, type safety, SwiftUI declarative user interfaces, UIKit interop, MVVM architecture, Core Data persistence, and App Store submission workflows.',
    tags: ['Swift', 'UIKit', 'SwiftUI', 'Architecture Patterns', 'Core Data', 'iOS Development', 'Swift iOS development course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 22,
    title: 'Mobile Cloud: Backend for Apps',
    slug: 'mobile-cloud-backend-for-apps',
    category: CourseCategory.MOBILE_DEVELOPMENT,
    subcategory: 'Backend for Mobile Applications',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['Firebase Firestore', 'Authentication', 'Realtime Database', 'Cloud Functions', 'REST APIs'],
    targetAudience: 'Mobile developers needing backend & cloud connectivity',
    prerequisites: 'AppStarter or basic mobile dev experience',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Completes the mobile stack; BaaS focus',
    suggestedKeyword: 'Firebase Supabase mobile backend',
    price: 3499,
    originalPrice: 6999,
    rating: 4.7,
    shortDescription: 'Completes the mobile stack; BaaS focus. Connect mobile apps to Firestore, Auth, and Cloud Functions.',
    description: 'Connect mobile apps with robust backend-as-a-service infrastructure. Master Firestore NoSQL database modeling, user authentication, security rules, serverless Cloud Functions, push notifications, and offline sync.',
    tags: ['Firebase Firestore', 'Authentication', 'Realtime Database', 'Cloud Functions', 'REST APIs', 'Mobile Cloud', 'Firebase Supabase mobile backend'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 23,
    title: 'UX Universe: Intro to User Experience',
    slug: 'ux-universe-intro-to-user-experience',
    category: CourseCategory.DESIGN,
    subcategory: 'UI/UX Principles & Tools',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Design Thinking', 'Wireframing', 'Figma Basics', 'Usability Principles', 'User Personas'],
    targetAudience: 'Non-designers & beginners; anyone making products',
    prerequisites: 'None — open to all backgrounds',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Low-barrier, appeals to non-CS students too',
    suggestedKeyword: 'UX Design course Guwahati',
    price: 2499,
    originalPrice: 4999,
    rating: 4.9,
    shortDescription: 'Low-barrier, appeals to non-CS students too. Master Design Thinking, Figma, and wireframing.',
    description: 'Foundations of human-centered digital product design. Learn user research methods, persona creation, customer journey maps, information architecture, paper wireframing, Figma basics, and usability evaluation heuristics.',
    tags: ['Design Thinking', 'Wireframing', 'Figma Basics', 'Usability Principles', 'User Personas', 'UI/UX', 'UX Design course Guwahati'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 24,
    title: 'FigmaPro: From Sketch to Screens',
    slug: 'figmapro-from-sketch-to-screens',
    category: CourseCategory.DESIGN,
    subcategory: 'UI/UX Principles & Tools',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['Advanced Figma', 'Design Systems', 'Components', 'Auto Layout', 'Prototyping'],
    targetAudience: 'Students with basic design sense wanting production-ready Figma skills',
    prerequisites: 'UX Universe or basic Figma familiarity',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Tool specific, portfolio builder',
    suggestedKeyword: 'Figma training course UI UX',
    price: 3499,
    originalPrice: 6999,
    rating: 4.9,
    shortDescription: 'Tool specific, portfolio builder. Master advanced Figma auto-layout, design systems, and components.',
    description: 'Elevate your UI craft to professional design system standards. Master Figma Auto-Layout v4, component properties, variant states, design tokens, typography scales, responsive grids, and advanced interactive prototypes.',
    tags: ['Figma', 'Design Systems', 'Components', 'Auto Layout', 'Prototyping', 'UI/UX', 'Figma training course UI UX'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 25,
    title: 'UX Lab: Micro-interactions and Testing',
    slug: 'ux-lab-micro-interactions-and-testing',
    category: CourseCategory.DESIGN,
    subcategory: 'UI/UX Principles & Tools',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Prototyping', 'Usability Testing', 'User Interviews', 'Micro-interactions', 'Heatmaps'],
    targetAudience: 'Aspiring UX researchers and senior designers',
    prerequisites: 'FigmaPro or intermediate UI/UX skills',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Advanced UX niche; research-oriented',
    suggestedKeyword: 'UX testing microinteractions course',
    price: 3499,
    originalPrice: 6999,
    rating: 4.8,
    shortDescription: 'Advanced UX niche; research-oriented. Master micro-interactions, usability tests, and heatmaps.',
    description: 'Advanced UX research and interaction engineering. Conduct qualitative user interviews, run moderated usability tests, analyze heatmap and clickstream analytics, and build micro-interaction prototypes using Smart Animate.',
    tags: ['Prototyping', 'Usability Testing', 'User Interviews', 'Micro-interactions', 'Heatmaps', 'UX Lab', 'UX testing microinteractions course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 26,
    title: 'GitFlow: Version Control 101',
    slug: 'gitflow-version-control-101',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Version Control, SDLC, Agile & Testing',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 12,
    lessonsCount: 10,
    keyTopics: ['Git Basics', 'Branching', 'GitHub Workflow', 'Pull Requests', 'Merge Conflicts'],
    targetAudience: 'All students; foundational skill for any tech track',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Universal & essential skill; every student needs this',
    suggestedKeyword: 'Git GitHub version control course',
    price: 1499,
    originalPrice: 2999,
    rating: 4.9,
    shortDescription: 'Universal & essential skill; every student needs this. Master Git terminal, GitHub, and branch merges.',
    description: 'The mandatory software engineering skill for every developer. Master command-line Git, staging trees, commit histories, remote repositories, feature branching strategies, pull requests, and resolving tricky merge conflicts.',
    tags: ['Git Basics', 'Branching', 'GitHub Workflow', 'Pull Requests', 'Merge Conflicts', 'Version Control', 'Git GitHub version control course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 27,
    title: 'AgileOps: Mastering Clean Code & Scrum',
    slug: 'agileops-mastering-clean-code-scrum',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Version Control, SDLC, Agile & Testing',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 24,
    lessonsCount: 18,
    keyTopics: ['Agile', 'Scrum', 'Code Reviews', 'Refactoring', 'Sprint Planning', 'Retrospectives'],
    targetAudience: 'Students entering software engineering project teams',
    prerequisites: 'Any project or team experience',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Professionalization angle; ready to join real agile teams',
    suggestedKeyword: 'Agile Scrum training developers',
    price: 2999,
    originalPrice: 5999,
    rating: 4.8,
    shortDescription: 'Professionalization angle; ready to join real agile teams. Master Scrum ceremonies and clean code.',
    description: 'Learn how modern software teams collaborate and ship quality software. Master Agile principles, Scrum ceremonies (sprints, standups, retro), user story estimation, code review standards, refactoring, and clean code patterns.',
    tags: ['Agile', 'Scrum', 'Code Reviews', 'Refactoring', 'Sprint Planning', 'Retrospectives', 'Clean Code', 'Agile Scrum training developers'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 28,
    title: 'SystemSprint: Design Scalable Apps',
    slug: 'systemsprint-design-scalable-apps',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'System Design',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 40,
    lessonsCount: 30,
    keyTopics: ['System Architecture', 'Microservices', 'Caching', 'Load Balancing', 'Database Sharding', 'High Availability'],
    targetAudience: 'Final-year students preparing for FAANG/product interviews',
    prerequisites: 'Strong programming + basic system knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Interview essential; FAANG prep',
    suggestedKeyword: 'System design course interview',
    price: 5499,
    originalPrice: 10999,
    rating: 4.9,
    shortDescription: 'Interview essential; FAANG prep. Master microservices, caching, sharding, and high availability.',
    description: 'High-scale distributed system design for senior software roles. Learn architectural blueprints for web scale, horizontal scaling, load balancing algorithms, Redis caching, database sharding, replication, and CAP trade-offs.',
    tags: ['System Architecture', 'Microservices', 'Caching', 'Load Balancing', 'Database Sharding', 'High Availability', 'System Design', 'System design course interview'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 29,
    title: 'Capstone Builder: Mini Portfolio Projects',
    slug: 'capstone-builder-mini-portfolio-projects',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Mini - Capstone Projects',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 15,
    keyTopics: ['Portfolio Website', 'Resume Site', 'Personal Blog', 'GitHub Profile Setup'],
    targetAudience: 'First-year students wanting to build an online presence',
    prerequisites: 'WebStart or basic HTML/CSS',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Early portfolio building; tangible output',
    suggestedKeyword: 'Portfolio projects course students',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'Early portfolio building; tangible output. Build personal portfolio, resume site, and GitHub profile.',
    description: 'Stand out from the crowd with deployed live projects. Build a personal developer portfolio showcase, interactive responsive resume website, markdown-based tech blog, and optimize your GitHub presence to impress recruiters.',
    tags: ['Portfolio Website', 'Resume Site', 'Personal Blog', 'GitHub Profile', 'Mini Projects', 'Web Development', 'Portfolio projects course students'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 30,
    title: 'CloneCraft: Reverse Engineer Apps',
    slug: 'clonecraft-reverse-engineer-apps',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Mini - Capstone Projects',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Clone Projects: Netflix/Spotify/Twitter Clones', 'Full-Stack Architecture'],
    targetAudience: 'Students with basic frontend/backend skills wanting portfolio pieces',
    prerequisites: 'All core web or mobile courses completed',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Bridge to real-world experience; clone credibility',
    suggestedKeyword: 'Build Netflix clone project',
    price: 3999,
    originalPrice: 7999,
    rating: 4.9,
    shortDescription: 'Bridge to real-world experience; clone credibility. Reverse engineer Netflix, Spotify, and Twitter.',
    description: 'Reverse engineer and code iconic commercial web applications. Learn how industry giants structure media streaming, news feeds, real-time messaging, audio playback, and complex state management across full-stack clones.',
    tags: ['Netflix Clone', 'Spotify Clone', 'Twitter Clone', 'Full-Stack Architecture', 'React', 'Node.js', 'Build Netflix clone project'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 31,
    title: 'RealWorld Pro: Startup Projects',
    slug: 'realworld-pro-startup-projects',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Capstone Projects',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 45,
    lessonsCount: 32,
    keyTopics: ['End-to-End Product Development', 'CI/CD', 'Deployment', 'Monitoring', 'Real User Testing'],
    targetAudience: 'Advanced students ready for client-facing / team-based project work',
    prerequisites: 'CloneCraft or equivalent real-project experience',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Real-client deliverables; high exposure',
    suggestedKeyword: 'Real-world startup project course',
    price: 5999,
    originalPrice: 11999,
    rating: 4.9,
    shortDescription: 'Real-client deliverables; high exposure. End-to-end product delivery, CI/CD, and live monitoring.',
    description: 'Simulate high-impact startup product engineering. Collaborate in sprint teams to architect, build, test, and ship complete commercial applications with automated CI/CD pipelines, live monitoring, and real user feedback loops.',
    tags: ['Product Development', 'CI/CD', 'Deployment', 'Monitoring', 'User Testing', 'Startup Projects', 'Real-world startup project course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 32,
    title: 'JobJumpstart: Resume + LinkedIn Mastery',
    slug: 'jobjumpstart-resume-linkedin-mastery',
    category: CourseCategory.BUSINESS,
    subcategory: 'Soft Skills & Interview Prep',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 16,
    lessonsCount: 12,
    keyTopics: ['Resume Writing', 'ATS Optimization', 'LinkedIn Optimization', 'Networking Tactics', 'Job Hunt Strategy'],
    targetAudience: 'All students, especially pre-placement years',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Immediate ROI; high demand; high placement rate',
    suggestedKeyword: 'Resume building LinkedIn course',
    price: 1999,
    originalPrice: 3999,
    rating: 4.9,
    shortDescription: 'Immediate ROI; high demand; high placement rate. ATS resume optimization and LinkedIn mastery.',
    description: 'Land job and internship callbacks faster. Learn how to write ATS-compliant technical resumes, craft compelling impact bullet points, optimize LinkedIn profiles for recruiter searches, and leverage outbound networking tactics.',
    tags: ['Resume Writing', 'ATS Optimization', 'LinkedIn Optimization', 'Networking Tactics', 'Job Hunt Strategy', 'Career Prep', 'Resume building LinkedIn course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 33,
    title: 'CrackIT: Tech Interviews + DSA Dynamics',
    slug: 'crackit-tech-interviews-dsa-dynamics',
    category: CourseCategory.PROGRAMMING,
    subcategory: 'Soft Skills & Interview Prep',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 24,
    lessonsCount: 18,
    keyTopics: ['Mock Technical Interviews', 'Problem-solving Strategies', 'Behavioral Questions', 'Salary Negotiation'],
    targetAudience: 'Final-year students preparing for tech interviews',
    prerequisites: 'AlgoCore or system design knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Placement-readiness ROI; interview driver',
    suggestedKeyword: 'Tech interview prep crash course',
    price: 3499,
    originalPrice: 6999,
    rating: 4.9,
    shortDescription: 'Placement-readiness ROI; interview driver. Live mock technical interviews and salary negotiation.',
    description: 'Overcome interview anxiety and convert interviews into offers. Participate in simulated live coding screens, master think-aloud problem-solving, deliver structured STAR behavioral responses, and negotiate compensation.',
    tags: ['Mock Technical Interviews', 'Problem-solving Strategies', 'Behavioral Questions', 'Salary Negotiation', 'DSA Dynamics', 'Tech interview prep crash course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 34,
    title: 'TechPrep: Leadership & Team Dynamics',
    slug: 'techprep-leadership-team-dynamics',
    category: CourseCategory.BUSINESS,
    subcategory: 'Soft Skills & Interview Prep',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 20,
    lessonsCount: 15,
    keyTopics: ['Soft Skills for Developers', 'Team Communication', 'Conflict Resolution', 'Presentation Skills', 'Engineering Leadership'],
    targetAudience: 'Students aspiring to tech lead / engineering manager roles',
    prerequisites: 'Any team project experience',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Soft-skills differentiation; many tech-heavy students lack this',
    suggestedKeyword: 'Tech leadership soft skills training',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'Soft-skills differentiation; many tech-heavy students lack this. Leadership and communication skills.',
    description: 'The critical human skills for senior engineering success. Master technical documentation, assertive team communication, resolving engineering disagreements, presenting architecture proposals, and guiding junior peers.',
    tags: ['Soft Skills', 'Team Communication', 'Conflict Resolution', 'Presentation Skills', 'Engineering Leadership', 'Tech leadership soft skills training'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 35,
    title: 'WP Wizard: WordPress from Scratch',
    slug: 'wp-wizard-wordpress-from-scratch',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Website CMS',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['WordPress Basics', 'Elementor', 'Theme Customization', 'Plugins', 'Hosting', 'SEO Setup'],
    targetAudience: 'Non-coders, freelancers, small business owners, beginners',
    prerequisites: 'Basic computer and internet literacy',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Freelancer pipeline; quick monetization story',
    suggestedKeyword: 'WordPress course for beginners India',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'Freelancer pipeline; quick monetization story. Build responsive websites with WordPress & Elementor.',
    description: 'Launch client websites in hours without writing code. Learn WordPress administration, domain and hosting setup, Elementor drag-and-drop page builder, theme customization, security hardening, and on-page SEO essentials.',
    tags: ['WordPress', 'Elementor', 'Theme Customization', 'Plugins', 'Hosting', 'SEO', 'CMS', 'WordPress course for beginners India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 36,
    title: 'E-commerce Magic: Store Setup',
    slug: 'ecommerce-magic-store-setup',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Website CMS',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 25,
    lessonsCount: 20,
    keyTopics: ['WooCommerce Setup', 'Payment Gateways', 'Checkout Flow', 'Inventory Management', 'Store Analytics'],
    targetAudience: 'WordPress owners wanting to sell online; aspiring freelance store builders',
    prerequisites: 'WP Wizard or basic WordPress knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'eCommerce demand; entrepreneur appeal',
    suggestedKeyword: 'WooCommerce online store course',
    price: 2999,
    originalPrice: 5999,
    rating: 4.8,
    shortDescription: 'eCommerce demand; entrepreneur appeal. Setup WooCommerce stores with payments and analytics.',
    description: 'Build complete e-commerce stores using WooCommerce. Master product variation cataloging, Razorpay/Stripe payment gateway integration, shipping zones, tax rules, inventory alerts, and e-commerce conversion tracking.',
    tags: ['WooCommerce', 'Payment Gateways', 'Checkout Flow', 'Inventory Management', 'Store Analytics', 'E-commerce', 'WooCommerce online store course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 37,
    title: 'WP Unchained: Headless CMS Build',
    slug: 'wp-unchained-headless-cms-build',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Project-Based CMS Builds',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Headless WordPress', 'GraphQL', 'REST API', 'React Frontend', 'Next.js Integration'],
    targetAudience: 'Developers wanting headless CMS architecture with modern frontend',
    prerequisites: 'WP Wizard + Javascript/React basics',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Cutting-edge CMS; developer credibility',
    suggestedKeyword: 'Headless WordPress React course',
    price: 3999,
    originalPrice: 7999,
    rating: 4.9,
    shortDescription: 'Cutting-edge CMS; developer credibility. Headless WordPress with GraphQL and Next.js frontend.',
    description: 'Decouple WordPress backend for blazing speed. Use WordPress as a headless content store via WPGraphQL and REST APIs, paired with modern React and Next.js frontends with Incremental Static Regeneration (ISR).',
    tags: ['Headless WordPress', 'GraphQL', 'REST API', 'React Frontend', 'Next.js Integration', 'Headless CMS', 'Headless WordPress React course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 38,
    title: 'Shopify Starter: Launch a Shop',
    slug: 'shopify-starter-launch-a-shop',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'E-commerce Platform',
    level: CourseLevel.BEGINNER,
    difficultyLevel: 'Beginner',
    duration: 20,
    lessonsCount: 16,
    keyTopics: ['Shopify Setup', 'Themes', 'Products', 'Payment Setup', 'Dropshipping Basics', 'App Store'],
    targetAudience: 'Non-coders, freelancers, aspiring e-commerce entrepreneurs',
    prerequisites: 'None',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Quick shop setup; e-commerce trends',
    suggestedKeyword: 'Shopify store setup course India',
    price: 2499,
    originalPrice: 4999,
    rating: 4.8,
    shortDescription: 'Quick shop setup; e-commerce trends. Launch and scale a modern Shopify online storefront.',
    description: 'Launch a profitable Shopify online business. Learn store configuration, theme customization, product cataloging, payment provider setups, essential Shopify app integrations, and dropshipping workflow setup.',
    tags: ['Shopify Setup', 'Themes', 'Products', 'Payment Setup', 'Dropshipping', 'App Store', 'Shopify', 'Shopify store setup course India'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 39,
    title: 'Liquid Mastery: Shopify Theme Dev',
    slug: 'liquid-mastery-shopify-theme-dev',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'E-commerce Platform',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 35,
    lessonsCount: 28,
    keyTopics: ['Liquid Templating', 'Shopify CLI', 'Theme Customization', 'Store Speed Optimization'],
    targetAudience: 'Developers wanting Shopify theme development skills',
    prerequisites: 'Basic HTML/CSS/JS',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Developer skills; freelance/agency demand',
    suggestedKeyword: 'Shopify Liquid theme development',
    price: 4499,
    originalPrice: 8999,
    rating: 4.9,
    shortDescription: 'Developer skills; freelance/agency demand. Master Liquid templating, Shopify CLI, and speed tuning.',
    description: 'Custom Shopify development for agencies and freelancers. Master the Liquid templating engine, Shopify CLI 3, JSON templates, dynamic sections, custom app extensions, and store Core Web Vitals optimization.',
    tags: ['Liquid Templating', 'Shopify CLI', 'Theme Customization', 'Speed Optimization', 'Shopify Developer', 'Shopify Liquid theme development'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 40,
    title: 'Shopify Headless: Hydrogen Projects',
    slug: 'shopify-headless-hydrogen-projects',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'E-commerce Platform',
    level: CourseLevel.ADVANCED,
    difficultyLevel: 'Advanced',
    duration: 40,
    lessonsCount: 30,
    keyTopics: ['Shopify Hydrogen', 'Oxygen', 'Storefront API', 'React Components', 'Headless Architecture'],
    targetAudience: 'E-commerce devs targeting high-performance custom storefronts',
    prerequisites: 'Liquid Mastery + React/Next.js knowledge',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Bleeding edge eCommerce; premium dev skill',
    suggestedKeyword: 'Shopify Hydrogen headless course',
    price: 5499,
    originalPrice: 10999,
    rating: 4.9,
    shortDescription: 'Bleeding edge eCommerce; premium dev skill. Build headless Shopify stores with Hydrogen and Oxygen.',
    description: 'Build lightning-fast headless e-commerce storefronts. Learn Shopify Hydrogen framework, Storefront GraphQL API, Oxygen global edge hosting, custom cart architectures, and sub-second page performance.',
    tags: ['Shopify Hydrogen', 'Oxygen', 'Storefront API', 'React Components', 'Headless Architecture', 'Shopify Hydrogen headless course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
  {
    sNo: 41,
    title: 'CMS Mix: Build & Deploy a Strapi CMS',
    slug: 'cms-mix-build-deploy-strapi-cms',
    category: CourseCategory.WEB_DEVELOPMENT,
    subcategory: 'Project-Based CMS Builds',
    level: CourseLevel.INTERMEDIATE,
    difficultyLevel: 'Intermediate',
    duration: 30,
    lessonsCount: 24,
    keyTopics: ['Strapi Headless', 'Content Modeling', 'REST/GraphQL APIs', 'Next.js Frontend Integration', 'Authentication'],
    targetAudience: 'Developers wanting open-source headless CMS experience',
    prerequisites: 'WP Wizard or Shopify Starter',
    deliveryMode: 'Offline / On-Campus',
    certificate: 'Yes - Course Completion',
    funnelTier: 'Tier 2',
    marketingAngle: 'Portable CMS skill; rapid project deployment',
    suggestedKeyword: 'CMS project deployment course',
    price: 3999,
    originalPrice: 7999,
    rating: 4.8,
    shortDescription: 'Portable CMS skill; rapid project deployment. Open-source Strapi Headless CMS with Next.js.',
    description: 'Build enterprise content architectures with open-source Strapi Headless CMS. Learn content collection modeling, relations, custom controllers and policies, REST & GraphQL endpoints, and Next.js frontend integration.',
    tags: ['Strapi Headless', 'Content Modeling', 'REST/GraphQL APIs', 'Next.js Frontend', 'Authentication', 'Headless CMS', 'CMS project deployment course'],
    instructor: { name: 'GrowthCraft Faculty' },
  },
];

async function seedCoursesSet1() {
  try {
    const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/growthcraft';
    await mongoose.connect(MONGODB_URI);
    logger.info('Connected to MongoDB');

    // 1. Initialize / Update CourseConfig for categories and levels
    const configDefaults = [
      {
        key: 'categories',
        values: [
          CourseCategory.PROGRAMMING,
          CourseCategory.WEB_DEVELOPMENT,
          CourseCategory.DATA_SCIENCE,
          CourseCategory.AI_ML,
          CourseCategory.DEVOPS,
          CourseCategory.CLOUD_COMPUTING,
          CourseCategory.CYBERSECURITY,
          CourseCategory.MOBILE_DEVELOPMENT,
          CourseCategory.DESIGN,
          CourseCategory.BUSINESS,
          CourseCategory.OTHER,
        ],
        isActive: true,
      },
      {
        key: 'difficultyLevels',
        values: ['Beginner', 'Intermediate', 'Advanced', 'Expert'],
        isActive: true,
      },
      {
        key: 'courseTypes',
        values: ['Course', 'Bootcamp'],
        isActive: true,
      },
    ];

    for (const config of configDefaults) {
      await CourseConfig.findOneAndUpdate(
        { key: config.key },
        { values: config.values, isActive: config.isActive },
        { new: true, upsert: true }
      ).exec();
    }
    logger.info('✓ Course configurations initialized & updated');

    // 2. Upsert each course from Courses - Set 1
    let inserted = 0;
    let updated = 0;

    for (const item of coursesSet1Data) {
      const existing = await Course.findOne({ slug: item.slug }).exec();

      const docData = {
        title: item.title,
        slug: item.slug,
        shortDescription: item.shortDescription,
        description: item.description,
        category: item.category,
        level: item.level,
        difficultyLevel: item.difficultyLevel,
        duration: item.duration,
        totalHours: item.duration,
        lessonsCount: item.lessonsCount,
        price: item.price,
        originalPrice: item.originalPrice,
        rating: item.rating,
        tags: item.tags,
        instructor: item.instructor,
        instructorId: item.instructor.name,
        enrollmentCount: Math.floor(Math.random() * 200) + 120, // realistic enrollment numbers
        isActive: true,
        isPublished: true,
        isDraft: false,
        publishedAt: new Date('2024-01-15T00:00:00.000Z'),
        type: 'Course',
      };

      await Course.findOneAndUpdate(
        { slug: item.slug },
        { $set: docData },
        { new: true, upsert: true, runValidators: true }
      ).exec();

      if (existing) {
        updated++;
      } else {
        inserted++;
      }
    }

    logger.info(`✓ Seeded ${coursesSet1Data.length} courses from Courses - Set 1 (${inserted} created, ${updated} updated)`);

    // 3. Print verification breakdown
    const totalCourses = await Course.countDocuments({ isPublished: true, isActive: true });
    console.log('\n=============================================');
    console.log('✓ Courses - Set 1 Seeding Complete');
    console.log(`Total Active & Published Courses: ${totalCourses}`);
    console.log('=============================================');

    const byCategory = await Course.aggregate([
      { $match: { isPublished: true, isActive: true } },
      { $group: { _id: '$category', count: { $sum: 1 } } },
      { $sort: { count: -1 } },
    ]);

    console.log('\nBreakdown by Category:');
    byCategory.forEach(cat => {
      console.log(`  • ${cat._id}: ${cat.count} courses`);
    });

    const byLevel = await Course.aggregate([
      { $match: { isPublished: true, isActive: true } },
      { $group: { _id: '$difficultyLevel', count: { $sum: 1 } } },
      { $sort: { count: -1 } },
    ]);

    console.log('\nBreakdown by Level:');
    byLevel.forEach(lvl => {
      console.log(`  • ${lvl._id}: ${lvl.count} courses`);
    });

    console.log('\n=============================================\n');

    process.exit(0);
  } catch (error) {
    logger.error('Error seeding Courses - Set 1:', error);
    process.exit(1);
  }
}

// Run seeder
seedCoursesSet1();
